"""Corrective Action Engine — generates platform-level corrective recommendations.

Analyzes content detection results, bias analysis, and trend data to produce
actionable corrective measures that promote an unbiased, transparent platform.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class CorrectiveAction:
    """A single corrective action recommendation."""

    action_id: str
    category: str          # labeling | suppression | transparency | escalation | education
    severity: str          # info | advisory | recommended | required
    title: str
    description: str
    rationale: str
    automated: bool = False  # can this be applied automatically?
    applied: bool = False
    applied_at: datetime | None = None


@dataclass
class CorrectiveReport:
    """Full corrective report for a piece of content or trend."""

    target_id: str                                # post_id or topic
    target_type: str                              # "post" | "trend"
    overall_risk: str                             # low | medium | high | critical
    trust_score: float                            # 0-100
    actions: list[CorrectiveAction] = field(default_factory=list)
    summary: str = ""
    generated_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class CorrectiveEngine:
    """Generates corrective actions for content and trends.

    Action categories:
    1. Labeling — Add appropriate labels (AI-generated, disputed, under review)
    2. Suppression — Reduce algorithmic amplification
    3. Transparency — Surface analysis results to users
    4. Escalation — Route to human review
    5. Education — Provide context about AI content and bias
    """

    def generate_post_corrections(
        self,
        post_id: str,
        *,
        ai_probability: float = 0.0,
        recommended_label: str = "human",
        is_author_declared: bool = False,
        bias_delta: float = 0.0,
        favoritism_flag: bool = False,
        dominant_agent: str | None = None,
        risk_factors: list[str] | None = None,
        community_ai_ratio: float = 0.0,
    ) -> CorrectiveReport:
        """Generate corrective actions for a single post."""
        actions: list[CorrectiveAction] = []
        risk_factors = risk_factors or []
        overall_risk = "low"
        trust_score = max(0, (1.0 - ai_probability) * 100)
        action_counter = 0

        def _add(cat: str, sev: str, title: str, desc: str, rationale: str, auto: bool = False) -> None:
            nonlocal action_counter
            action_counter += 1
            actions.append(
                CorrectiveAction(
                    action_id=f"{post_id}-CA-{action_counter:03d}",
                    category=cat,
                    severity=sev,
                    title=title,
                    description=desc,
                    rationale=rationale,
                    automated=auto,
                )
            )

        # ── AI Content Labeling ──
        if recommended_label in ("ai-generated", "likely-ai"):
            overall_risk = "high" if recommended_label == "ai-generated" else "medium"

            if not is_author_declared:
                _add(
                    "labeling", "required",
                    "Apply 'AI Content' Label",
                    "Attach a visible 'AI Content' badge to this post. "
                    "Users should know this content was likely generated by AI.",
                    f"AI detection probability: {ai_probability:.0%}. "
                    f"Author did not self-declare. Platform transparency policy requires labeling.",
                    auto=True,
                )
                _add(
                    "transparency", "recommended",
                    "Show AI Detection Analysis",
                    "Display the AI detection breakdown (linguistic, structural, statistical signals) "
                    "to users who click the AI label.",
                    "Empowering users with evidence supports informed engagement.",
                )
            else:
                _add(
                    "labeling", "info",
                    "Confirm Author AI Declaration",
                    "Author correctly self-declared this as AI content. "
                    "Maintain the existing AI label.",
                    "Author transparency verified — no corrective action needed for labeling.",
                    auto=True,
                )

            _add(
                "suppression", "recommended",
                "Reduce Algorithmic Amplification",
                "Reduce this post's weight in recommendation algorithms by 30-50%. "
                "AI content should not be amplified at the same rate as organic human content.",
                f"AI probability {ai_probability:.0%} exceeds amplification threshold. "
                "Reducing amplification prevents AI content from dominating feeds.",
                auto=True,
            )

        elif recommended_label == "uncertain":
            overall_risk = "medium"
            _add(
                "labeling", "recommended",
                "Apply 'Disputed Origin' Label",
                "Mark this content as having disputed AI/human origin. "
                "Show the community vote breakdown to users.",
                f"AI probability {ai_probability:.0%} is in the uncertain range. "
                "Transparent labeling helps users make their own judgment.",
                auto=True,
            )
            _add(
                "escalation", "advisory",
                "Flag for Community Review",
                "Promote this post in the Content Review queue for community analysis.",
                "Disputed content benefits from additional human perspectives.",
            )

        # ── Bias Corrections ──
        if favoritism_flag:
            severity_for_bias = "required" if bias_delta > 0.2 else "recommended"
            if overall_risk == "low":
                overall_risk = "medium"
            if bias_delta > 0.25:
                overall_risk = "high"

            _add(
                "transparency", severity_for_bias,
                "Show Debiased Score",
                f"Display the debiased score alongside the original to show the {bias_delta:.0%} "
                f"bias correction. Dominant agent: {dominant_agent or 'unknown'}.",
                f"Regional bias favoritism detected (delta: {bias_delta:.3f}). "
                "Users deserve to see both the biased and corrected assessment.",
            )
            _add(
                "education", "advisory",
                "Show Bias Explanation",
                "Provide educational context about how regional cultural biases "
                "can inflate or deflate AI detection scores.",
                "Understanding bias helps users critically evaluate AI analysis results.",
            )

        # ── Community Discrepancy ──
        if community_ai_ratio > 0.7 and not is_author_declared and recommended_label in ("likely-human", "human"):
            _add(
                "escalation", "recommended",
                "Investigate Community-Declaration Gap",
                f"Community flags {community_ai_ratio:.0%} AI, but detection says {recommended_label}. "
                "Route to expert review to resolve the discrepancy.",
                "Significant gap between community consensus and automated detection warrants investigation.",
            )
            if overall_risk == "low":
                overall_risk = "medium"

        # ── Engagement Manipulation Risk ──
        if "Very high AI probability" in " ".join(risk_factors):
            _add(
                "suppression", "required",
                "Prevent Viral Amplification",
                "Block this content from being featured in 'trending' or 'for you' feeds. "
                "AI-generated content with very high probability should not go viral through algorithmic channels.",
                "Platform integrity requires preventing AI content from being virally amplified "
                "as if it were organic.",
                auto=True,
            )
            overall_risk = "critical"

        # ── Education (always) ──
        if actions:
            _add(
                "education", "info",
                "AI Content Awareness",
                "This post has been analyzed by TrustFeed's multi-signal AI detection system. "
                "Detection combines linguistic analysis, structural patterns, statistical signals, "
                "community consensus, and multi-agent bias evaluation.",
                "Transparency about the detection process builds user trust in the platform.",
            )

        trust_score = max(0, min(100, trust_score - len(risk_factors) * 5))
        if favoritism_flag:
            trust_score = max(0, trust_score - bias_delta * 50)

        summary = self._build_summary(post_id, overall_risk, actions, ai_probability, bias_delta)

        return CorrectiveReport(
            target_id=post_id,
            target_type="post",
            overall_risk=overall_risk,
            trust_score=round(trust_score, 2),
            actions=actions,
            summary=summary,
        )

    def generate_trend_corrections(
        self,
        topic: str,
        *,
        ai_ratio: float = 0.0,
        velocity: float = 0.0,
        coordination_score: float = 0.0,
        unique_authors: int = 0,
        post_count: int = 0,
        trust_score: float = 100.0,
        circuit_broken: bool = False,
    ) -> CorrectiveReport:
        """Generate corrective actions for a trending topic."""
        actions: list[CorrectiveAction] = []
        overall_risk = "low"
        counter = 0

        def _add(cat: str, sev: str, title: str, desc: str, rationale: str, auto: bool = False) -> None:
            nonlocal counter
            counter += 1
            actions.append(
                CorrectiveAction(
                    action_id=f"trend-{topic}-CA-{counter:03d}",
                    category=cat,
                    severity=sev,
                    title=title,
                    description=desc,
                    rationale=rationale,
                    automated=auto,
                )
            )

        if circuit_broken:
            overall_risk = "critical"
            _add(
                "suppression", "required",
                "Trend Circuit Broken",
                f"'{topic}' has been removed from trending. All posts under this topic "
                "are labeled 'Under Review'. New engagement is throttled.",
                f"Trust score: {trust_score:.0f}/100. Multiple anomaly signals triggered the circuit breaker.",
                auto=True,
            )

        if ai_ratio >= 0.75:
            overall_risk = "critical" if overall_risk != "critical" else overall_risk
            _add(
                "labeling", "required",
                "Label as AI-Driven Trend",
                f"Apply 'AI-Driven Trend' label — {ai_ratio:.0%} of posts are AI-generated.",
                "Users should know this trend is primarily driven by artificial content.",
                auto=True,
            )
        elif ai_ratio >= 0.50:
            overall_risk = max(overall_risk, "high")
            _add(
                "transparency", "recommended",
                "Show AI Content Ratio",
                f"Display '{ai_ratio:.0%} AI Content' indicator on the trending topic.",
                "Transparency about AI involvement helps users contextualize the trend.",
            )

        if coordination_score > 0.70:
            overall_risk = max(overall_risk, "high")
            _add(
                "escalation", "required",
                "Investigate Coordinated Amplification",
                f"Coordination score: {coordination_score:.0%}. Timing patterns suggest "
                "organized campaign. Route to Trust & Safety team.",
                "Coordinated inauthentic behavior threatens platform integrity.",
            )

        if post_count >= 5 and unique_authors / max(1, post_count) < 0.2:
            _add(
                "escalation", "recommended",
                "Low Author Diversity Alert",
                f"Only {unique_authors} unique authors for {post_count} posts. "
                "Investigate for sock puppet / multi-account abuse.",
                "Genuine trends have diverse participation.",
            )

        if velocity > 10:
            _add(
                "suppression", "recommended",
                "Throttle Engagement Velocity",
                f"Current velocity: {velocity:.1f} posts/min. Apply rate limiting "
                "to new posts and reduce algorithmic boost.",
                "Unnatural velocity spikes indicate manipulation or bot activity.",
                auto=True,
            )

        summary_parts = []
        if circuit_broken:
            summary_parts.append(f"CIRCUIT BROKEN: '{topic}' removed from trending.")
        summary_parts.append(
            f"Risk: {overall_risk.upper()}. Trust: {trust_score:.0f}/100. "
            f"AI ratio: {ai_ratio:.0%}. Velocity: {velocity:.1f}/min. "
            f"{len(actions)} corrective actions recommended."
        )

        return CorrectiveReport(
            target_id=topic,
            target_type="trend",
            overall_risk=overall_risk,
            trust_score=trust_score,
            actions=actions,
            summary=" ".join(summary_parts),
        )

    @staticmethod
    def _build_summary(
        post_id: str,
        risk: str,
        actions: list[CorrectiveAction],
        ai_prob: float,
        bias_delta: float,
    ) -> str:
        required = sum(1 for a in actions if a.severity == "required")
        recommended = sum(1 for a in actions if a.severity == "recommended")
        parts = [f"Post {post_id}: Risk {risk.upper()}."]
        if ai_prob > 0.5:
            parts.append(f"AI probability {ai_prob:.0%}.")
        if bias_delta > 0.1:
            parts.append(f"Bias delta {bias_delta:.3f}.")
        parts.append(f"{required} required + {recommended} recommended actions.")
        return " ".join(parts)
