import { Component, inject, signal } from '@angular/core';
import { DecimalPipe, UpperCasePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SurveyService } from '../../services/survey.service';
import { SurveyResultsComponent } from '../survey-results/survey-results.component';
import { ErrorNotificationService } from '../../services/error-notification.service';
import { ImgFallbackDirective } from '../../utils/img-fallback.directive';
import { VideoFallbackDirective } from '../../utils/video-fallback.directive';

@Component({
  selector: 'app-survey',
  standalone: true,
  imports: [FormsModule, SurveyResultsComponent, DecimalPipe, UpperCasePipe, ImgFallbackDirective, VideoFallbackDirective],
  template: `
    <!-- Survey Landing / Start Screen -->
    @if (!surveyService.isActive() && !surveyService.isComplete() && !surveyService.loading()) {
    <div class="survey-container">
      <div class="survey-landing">
        <div class="landing-header">
          <span class="landing-icon">📋</span>
          <h1>Human-in-the-Loop AI Research Survey</h1>
          <p class="landing-subtitle">Data Authenticity Assessment — Can you tell AI from Human?</p>
        </div>

        <div class="landing-description">
          <div class="research-badge">
            <span class="rb-icon">🔬</span>
            <span>Research Protocol</span>
          </div>
          <p>
            This survey is part of a research study on <strong>Human-AI Collaboration</strong> for data authenticity.
            You will be shown content from the TrustLoop platform and asked to determine whether each item was
            created by a human or generated by AI. Seven continental AI bias agents will independently analyze the
            same content — your results will be compared with theirs.
          </p>

          <div class="info-cards">
            <div class="info-card">
              <span class="ic-icon">🎯</span>
              <h4>Your Task</h4>
              <p>Read each content item carefully and decide: AI-generated or human-created?</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">🌍</span>
              <h4>7 AI Agents</h4>
              <p>Africa, Asia, Europe, N. America, S. America, Antarctica & Australia agents each give unique verdicts</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">🤝</span>
              <h4>Human-AI Collab</h4>
              <p>Optional: see agent hints while you answer to study collaboration effects</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">📊</span>
              <h4>Results Dashboard</h4>
              <p>Compare your accuracy vs. each AI agent after completing the survey</p>
            </div>
          </div>
        </div>

        <div class="survey-config">
          <h3>Start Your Session</h3>
          <div class="config-row">
            <label>Mode</label>
            <div class="config-options">
              <button [class.active]="!collabMode" (click)="collabMode = false" class="config-btn mode-btn">
                <span>👤</span> Solo (Human Only)
              </button>
              <button [class.active]="collabMode" (click)="collabMode = true" class="config-btn mode-btn collab">
                <span>🤝</span> Human-AI Collab
              </button>
            </div>
          </div>
          @if (collabMode) {
          <p class="collab-note">
            In <strong>Human-AI Collab</strong> mode, you'll see agent verdicts <em>before</em> making your decision.
            This measures how AI assistance affects human judgment accuracy.
          </p>
          }
          <button class="start-btn" (click)="startSurvey()">
            <span>🚀</span> Begin Research Survey
          </button>
        </div>

        <div class="consent-notice">
          <span class="consent-icon">🔒</span>
          <p>You have provided informed consent. No personal data is collected or transmitted.</p>
        </div>
      </div>
    </div>
    }

    <!-- Loading Screen — Fetching unique content from internet -->
    @if (surveyService.loading()) {
    <div class="survey-container">
      <div class="loading-screen">
        <div class="loading-spinner"></div>
        <h2>Loading Content from Dataset</h2>
        <p>Loading curated content from 7 continental datasets...</p>
        <div class="loading-sources">
          <span class="source-tag">🌍 Africa</span>
          <span class="source-tag">🌏 Asia</span>
          <span class="source-tag">🇪🇺 Europe</span>
          <span class="source-tag">🌎 N. America</span>
          <span class="source-tag">🌎 S. America</span>
          <span class="source-tag">🧊 Antarctica</span>
          <span class="source-tag">🦘 Australia</span>
        </div>
      </div>
    </div>
    }

    <!-- Active Survey -->
    @if (surveyService.isActive()) {
    @let session = surveyService.session();
    @if (session) {
    <div class="survey-container">
      <div class="survey-progress">
        <div class="progress-info">
          <span class="progress-label">Progress</span>
          <span class="progress-count">{{ surveyService.progress().current }} / {{ surveyService.progress().total }}</span>
        </div>
        <div class="progress-bar">
          <div class="progress-fill" [style.width.%]="surveyService.progress().percent"></div>
        </div>
        <div class="progress-items">
          @for (item of session.items; track $index) {
          <button
            class="progress-dot"
            [class.answered]="item.humanVerdict != null"
            [class.current]="$index === session.currentIndex"
            [class.correct]="item.humanVerdict != null && item.humanVerdict === item.groundTruth"
            [class.wrong]="item.humanVerdict != null && item.humanVerdict !== item.groundTruth"
            (click)="surveyService.goToItem($index)">
            {{ $index + 1 }}
          </button>
          }
        </div>
      </div>

      <!-- Current Item -->
      @let item = surveyService.currentItem();
      @if (item) {
      <div class="survey-item">
        <div class="item-header">
          <span class="item-number">Item {{ session.currentIndex + 1 }}</span>
          <span class="item-category">{{ item.category }}</span>
          <span class="item-difficulty" [class]="'diff-' + item.difficulty">{{ item.difficulty }}</span>
          <span class="item-type">{{ item.contentType }}</span>
        </div>

        <div class="item-content-card">
          <h3 class="item-title">{{ item.title }}</h3>
          <p class="item-content">{{ item.content }}</p>
          @if (item.imageUrl && item.contentType !== 'video') {
          <img [src]="item.imageUrl" alt="Survey content image" class="item-image" appImgFallback="survey-item" />
          }
          @if (item.contentType === 'video' && item.videoUrl) {
          <div class="item-video-wrap">
            <video controls [poster]="item.imageUrl || ''" class="item-video" appVideoFallback="survey-video">
              <source [src]="item.videoUrl" type="video/mp4">
              Your browser does not support video playback.
            </video>
          </div>
          }
          @if (item.contentType === 'video' && !item.videoUrl && item.imageUrl) {
          <img [src]="item.imageUrl" alt="Video thumbnail" class="item-image" appImgFallback="video-thumbnail" />
          }
        </div>

        <!-- Human-AI Collab: Agent Hints (shown before answering in collab mode) -->
        @if (session.collabMode && item.humanVerdict == null) {
        <div class="collab-hints">
          <!-- AI Influence Alert for Investigator -->
          <div class="ai-influence-alert">
            <div class="aia-icon-area">
              <span class="aia-pulse"></span>
              <span class="aia-icon">🧠</span>
            </div>
            <div class="aia-body">
              <span class="aia-title">AI-Influenced Suggestions Below</span>
              <span class="aia-detail">The following verdicts are generated by regionally-biased AI agents. These are AI-influenced suggestions — not ground truth. Consider potential biases before adopting agent recommendations.</span>
            </div>
            <span class="aia-badge" [class.consensus]="getAgentConsensus(item.agentVerdicts)">
              {{ getAgentConsensus(item.agentVerdicts) ? '⚡ CONSENSUS' : '⚖️ SPLIT' }}
            </span>
          </div>

          <div class="collab-header">
            <span class="collab-icon">🤝</span>
            <span class="collab-title">Human-AI Collaboration Mode — Agent Hints</span>
          </div>
          <div class="agent-hints-grid">
            @for (av of item.agentVerdicts; track av.region) {
            <div class="agent-hint">
              <div class="hint-header">
                <span class="hint-flag">{{ getRegionFlag(av.region) }}</span>
                <span class="hint-region">{{ av.region }}</span>
                <span class="hint-verdict" [class]="'v-' + av.verdict">{{ av.verdict | uppercase }}</span>
                <span class="hint-conf">{{ av.confidence * 100 | number:'1.0-0' }}%</span>
              </div>
              @if (av.analysisImageUrl || av.analysisVideoUrl) {
              <div class="hint-media">
                @if (av.analysisMediaType === 'video' && av.analysisVideoUrl) {
                <video [src]="av.analysisVideoUrl" [poster]="av.analysisImageUrl" controls muted class="agent-media-video" appVideoFallback="agent-video" [agentRegion]="av.region"></video>
                }
                @if (av.analysisMediaType === 'image' && av.analysisImageUrl) {
                <img [src]="av.analysisImageUrl" alt="Agent analysis media" class="agent-media-img" loading="lazy" appImgFallback="agent-media" [agentRegion]="av.region" />
                }
              </div>
              }
              <p class="hint-reasoning">{{ av.reasoning }}</p>
            </div>
            }
          </div>
        </div>
        }

        <!-- Already-answered review -->
        @if (item.humanVerdict != null) {
        <div class="already-answered">
          <div class="answer-summary" [class.correct]="item.humanVerdict === item.groundTruth" [class.wrong]="item.humanVerdict !== item.groundTruth">
            <span class="answer-icon">{{ item.humanVerdict === item.groundTruth ? '✅' : '❌' }}</span>
            <div class="answer-details">
              <span>Your answer: <strong>{{ item.humanVerdict | uppercase }}</strong></span>
              <span>Truth: <strong>{{ item.groundTruth | uppercase }}</strong></span>
            </div>
          </div>
          <!-- Show all agent verdicts after answering -->
          <div class="post-answer-agents">
            <h4>🌍 Agent Verdicts</h4>
            <!-- AI Influence Indicator -->
            <div class="ai-influence-summary">
              <span class="ais-icon">🧠</span>
              <span class="ais-text">These AI agent verdicts influenced the collaborative analysis. Majority verdict: <strong>{{ getMajorityVerdict(item.agentVerdicts) | uppercase }}</strong></span>
              <span class="ais-match" [class.match]="getMajorityVerdict(item.agentVerdicts) === item.groundTruth" [class.mismatch]="getMajorityVerdict(item.agentVerdicts) !== item.groundTruth">
                {{ getMajorityVerdict(item.agentVerdicts) === item.groundTruth ? '✅ Correct' : '❌ Wrong' }}
              </span>
            </div>
            <div class="agent-grid-review">
              @for (av of item.agentVerdicts; track av.region) {
              <div class="agent-review-card"
                [class.agent-correct]="av.verdict === item.groundTruth"
                [class.agent-wrong]="av.verdict !== item.groundTruth">
                <div class="arc-header">
                  <span>{{ getRegionFlag(av.region) }} {{ av.region }}</span>
                  <span class="arc-verdict" [class]="'v-' + av.verdict">{{ av.verdict | uppercase }}</span>
                  <span class="arc-result">{{ av.verdict === item.groundTruth ? '✅' : '❌' }}</span>
                </div>
                @if (av.analysisImageUrl || av.analysisVideoUrl) {
                <div class="agent-review-media">
                  @if (av.analysisMediaType === 'video' && av.analysisVideoUrl) {
                  <video [src]="av.analysisVideoUrl" [poster]="av.analysisImageUrl" controls muted class="agent-media-video" appVideoFallback="agent-review-video" [agentRegion]="av.region"></video>
                  }
                  @if (av.analysisMediaType === 'image' && av.analysisImageUrl) {
                  <img [src]="av.analysisImageUrl" alt="Agent analysis media" class="agent-media-img" loading="lazy" appImgFallback="agent-review-media" [agentRegion]="av.region" />
                  }
                </div>
                }
                <div class="arc-conf">Confidence: {{ av.confidence * 100 | number:'1.0-0' }}%</div>
                <p class="arc-reasoning">{{ av.reasoning }}</p>
              </div>
              }
            </div>
          </div>
        </div>
        }

        <!-- Verdict Input (only show if not yet answered) -->
        @if (item.humanVerdict == null) {
        <div class="verdict-input">
          <h3 class="verdict-question">Is this content AI-generated or human-created?</h3>

          <div class="verdict-buttons">
            <button class="verdict-btn ai-btn" [class.selected]="pendingVerdict === 'ai'" (click)="pendingVerdict = 'ai'">
              <span class="vb-icon">🤖</span>
              <span class="vb-label">AI Generated</span>
            </button>
            <button class="verdict-btn human-btn" [class.selected]="pendingVerdict === 'human'" (click)="pendingVerdict = 'human'">
              <span class="vb-icon">👤</span>
              <span class="vb-label">Human Created</span>
            </button>
          </div>

          @if (pendingVerdict) {
          <div class="confidence-input">
            <label>Confidence Level</label>
            <div class="confidence-scale">
              @for (c of [1,2,3,4,5]; track c) {
              <button
                class="conf-btn"
                [class.selected]="pendingConfidence === c"
                (click)="pendingConfidence = c">
                {{ c }}
              </button>
              }
            </div>
            <div class="conf-labels">
              <span>Not sure</span>
              <span>Very confident</span>
            </div>
          </div>
          }

          @if (pendingVerdict) {
          <div class="reasoning-input">
            <label>Why do you think so? (optional)</label>
            <textarea [(ngModel)]="pendingReasoning" placeholder="Describe what clues led to your decision..." rows="3"></textarea>
          </div>
          }

          <button class="submit-btn" [disabled]="!pendingVerdict || !pendingConfidence" (click)="submitAnswer()">
            {{ isLastItem() ? '✅ Submit & View Results' : '➡️ Submit & Next' }}
          </button>

          <!-- Honeypot: hidden from real users, bots fill this -->
          <div class="visually-hidden" aria-hidden="true" style="position:absolute;left:-9999px;top:-9999px;height:0;width:0;overflow:hidden;">
            <label for="survey_website">Leave this blank</label>
            <input type="text" id="survey_website" name="website" [(ngModel)]="honeypot" tabindex="-1" autocomplete="off" />
          </div>
        </div>
        }
      </div>
      }
    </div>
    }
    }

    <!-- Results Dashboard -->
    @if (surveyService.isComplete()) {
    <app-survey-results />
    }
  `,
  styles: [`
    .survey-container {
      max-width: 900px;
      margin: 0 auto;
      padding: 2rem;
    }
    .survey-landing {
      display: flex;
      flex-direction: column;
      gap: 2rem;
    }
    .landing-header {
      text-align: center;
      .landing-icon { font-size: 3rem; display: block; margin-bottom: 1rem; }
      h1 { margin: 0 0 0.5rem; font-size: 2rem; color: var(--text-primary); font-weight: 700; }
      .landing-subtitle { color: var(--text-muted); font-size: 1.1rem; margin: 0; }
    }
    .landing-description {
      background: var(--bg-secondary);
      border-radius: var(--radius-lg); padding: 2rem; border: 1px solid var(--border-subtle);
      p { color: var(--text-secondary); line-height: 1.8; font-size: 0.95rem; margin: 1rem 0 1.5rem; }
    }
    .research-badge {
      display: inline-flex; align-items: center; gap: 0.5rem;
      background: var(--cat-a-bg); border: 1px solid var(--accent-primary);
      padding: 0.4rem 1rem; border-radius: var(--radius-full); color: var(--accent-primary);
      font-size: 0.8rem; font-weight: 600;
      .rb-icon { font-size: 1rem; }
    }
    .info-cards {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem;
    }
    .info-card {
      background: var(--bg-glass); border-radius: var(--radius-md); padding: 1.25rem;
      border: 1px solid var(--border-subtle); text-align: center;
      .ic-icon { font-size: 2rem; display: block; margin-bottom: 0.5rem; }
      h4 { margin: 0 0 0.4rem; color: var(--text-primary); font-size: 0.9rem; }
      p { margin: 0; color: var(--text-muted); font-size: 0.75rem; line-height: 1.5; }
    }
    .survey-config {
      background: var(--bg-secondary);
      border-radius: var(--radius-lg); padding: 2rem; border: 1px solid var(--border-subtle);
      h3 { margin: 0 0 1.5rem; color: var(--text-primary); font-size: 1.1rem; }
    }
    .config-row {
      margin-bottom: 1.25rem;
      label { display: block; color: var(--text-muted); font-size: 0.85rem; margin-bottom: 0.5rem; font-weight: 500; }
    }
    .config-options { display: flex; gap: 0.5rem; flex-wrap: wrap; }
    .config-fixed {
      background: var(--bg-glass); border: 1px solid var(--accent-primary);
      color: var(--accent-primary); padding: 0.6rem 1.25rem; border-radius: var(--radius-md);
      font-size: 0.9rem; font-weight: 600;
    }
    .config-btn {
      background: var(--bg-glass); border: 1px solid var(--border-default);
      color: var(--text-secondary); padding: 0.6rem 1.25rem; border-radius: var(--radius-md); cursor: pointer;
      font-size: 0.9rem; transition: all 0.3s; min-height: var(--min-touch-target);
      &:hover { background: var(--bg-elevated); }
      &.active {
        background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary)); color: var(--text-inverse);
        font-weight: 600; border-color: transparent;
      }
    }
    .mode-btn {
      display: flex; align-items: center; gap: 0.5rem;
      &.collab.active { background: linear-gradient(135deg, var(--accent-tertiary), var(--accent-primary)); color: var(--text-inverse); }
    }
    .collab-note {
      background: var(--cat-c-bg); border: 1px solid var(--accent-tertiary);
      padding: 0.75rem 1rem; border-radius: var(--radius-md); font-size: 0.82rem;
      color: var(--accent-tertiary); margin: 0.5rem 0 1rem; line-height: 1.5;
    }
    .start-btn {
      width: 100%; padding: 1rem; border: none; border-radius: var(--radius-md); cursor: pointer;
      background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary)); color: var(--text-inverse);
      font-size: 1.1rem; font-weight: 700; display: flex; align-items: center;
      justify-content: center; gap: 0.5rem; transition: all 0.3s; min-height: var(--min-touch-target);
      &:hover { transform: translateY(-2px); box-shadow: var(--shadow-lg); }
    }
    .consent-notice {
      display: flex; align-items: flex-start; gap: 0.75rem;
      background: var(--bg-glass); border-radius: var(--radius-md); padding: 1rem 1.5rem;
      border: 1px solid var(--border-subtle);
      .consent-icon { font-size: 1.25rem; flex-shrink: 0; margin-top: 2px; }
      p { margin: 0; color: var(--text-muted); font-size: 0.78rem; line-height: 1.6; }
    }
    .survey-progress {
      background: var(--bg-secondary);
      border-radius: var(--radius-lg); padding: 1.25rem 1.5rem; margin-bottom: 1.5rem;
      border: 1px solid var(--border-subtle);
    }
    .progress-info {
      display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem;
    }
    .progress-label { font-size: 0.8rem; color: var(--text-muted); }
    .progress-count { font-size: 0.85rem; color: var(--accent-primary); font-weight: 600; }
    .progress-bar {
      height: 6px; background: var(--bg-elevated); border-radius: 3px; overflow: hidden;
      margin-bottom: 0.75rem;
    }
    .progress-fill {
      height: 100%; background: linear-gradient(90deg, var(--accent-primary), var(--accent-secondary));
      border-radius: 3px; transition: width 0.4s;
    }
    .progress-items { display: flex; gap: 0.35rem; flex-wrap: wrap; }
    .progress-dot {
      width: 28px; height: 28px; border-radius: 50%; border: 1px solid var(--border-default);
      background: var(--bg-glass); color: var(--text-muted); font-size: 0.65rem;
      cursor: pointer; display: flex; align-items: center; justify-content: center;
      transition: all 0.2s;
      &.current { border-color: var(--accent-primary); color: var(--accent-primary); background: var(--cat-a-bg); }
      &.answered { border-color: var(--accent-secondary); }
      &.correct { background: var(--status-confirm-bg); color: var(--status-confirm); border-color: var(--status-confirm); }
      &.wrong { background: var(--status-critical-bg); color: var(--status-critical); border-color: var(--status-critical); }
    }
    .survey-item {
      display: flex; flex-direction: column; gap: 1.25rem;
    }
    .item-header {
      display: flex; align-items: center; gap: 0.75rem; flex-wrap: wrap;
    }
    .item-number {
      font-size: 0.85rem; color: var(--accent-primary); font-weight: 600;
      background: var(--cat-a-bg); padding: 0.3rem 0.75rem; border-radius: var(--radius-sm);
    }
    .item-category {
      font-size: 0.75rem; color: var(--text-secondary); background: var(--bg-glass);
      padding: 0.2rem 0.6rem; border-radius: var(--radius-sm);
    }
    .item-difficulty {
      font-size: 0.65rem; font-weight: 700; padding: 0.2rem 0.5rem; border-radius: var(--radius-sm);
      text-transform: uppercase; letter-spacing: 0.5px;
      &.diff-easy { background: var(--status-confirm-bg); color: var(--status-confirm); }
      &.diff-medium { background: var(--status-notice-bg); color: var(--status-notice); }
      &.diff-hard { background: var(--status-critical-bg); color: var(--status-critical); }
    }
    .item-type {
      font-size: 0.65rem; color: var(--text-muted); background: var(--bg-glass);
      padding: 0.2rem 0.5rem; border-radius: var(--radius-sm);
    }
    .item-content-card {
      background: var(--bg-secondary);
      border-radius: var(--radius-lg); padding: 2rem; border: 1px solid var(--border-subtle);
    }
    .item-title {
      margin: 0 0 1rem; color: var(--text-primary); font-size: 1.2rem; font-weight: 600;
    }
    .item-content {
      margin: 0; color: var(--text-secondary); font-size: 1rem; line-height: 1.8;
    }
    .item-image {
      width: 100%; border-radius: var(--radius-md); margin-top: 1rem; max-height: 400px; object-fit: cover;
    }
    .collab-hints {
      background: linear-gradient(135deg, var(--cat-c-bg), var(--cat-a-bg));
      border-radius: var(--radius-md); padding: 1.25rem; border: 1px solid var(--accent-tertiary);
    }
    /* AI Influence Alert */
    .ai-influence-alert {
      display: flex; align-items: flex-start; gap: 0.75rem;
      background: linear-gradient(135deg, var(--cat-a-bg), var(--cat-c-bg));
      border: 1px solid var(--accent-primary); border-radius: var(--radius-md);
      padding: 0.85rem 1rem; margin-bottom: 1rem;
      animation: fadeIn 0.5s ease-out;
    }
    .aia-icon-area {
      position: relative; flex-shrink: 0;
    }
    .aia-pulse {
      position: absolute; top: -3px; left: -3px; right: -3px; bottom: -3px;
      border-radius: 50%; background: var(--cat-a-bg);
      animation: pulse 2s ease-in-out infinite;
    }
    .aia-icon { position: relative; font-size: 1.2rem; z-index: 1; }
    .aia-body { flex: 1; }
    .aia-title {
      display: block; font-size: 0.78rem; font-weight: 700; color: var(--accent-primary); margin-bottom: 0.2rem;
    }
    .aia-detail { font-size: 0.7rem; color: var(--text-muted); line-height: 1.5; }
    .aia-badge {
      font-size: 0.6rem; font-weight: 700; padding: 0.2rem 0.5rem; border-radius: var(--radius-sm);
      white-space: nowrap; flex-shrink: 0;
      background: var(--status-notice-bg); color: var(--status-notice); border: 1px solid var(--status-notice);
      &.consensus { background: var(--cat-a-bg); color: var(--accent-primary); border-color: var(--accent-primary); }
    }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
    /* AI Influence Summary (post-answer) */
    .ai-influence-summary {
      display: flex; align-items: center; gap: 0.5rem;
      background: var(--cat-a-bg); border: 1px solid var(--accent-primary);
      border-radius: var(--radius-md); padding: 0.6rem 0.85rem; margin-bottom: 0.7rem;
    }
    .ais-icon { font-size: 0.9rem; flex-shrink: 0; }
    .ais-text { font-size: 0.72rem; color: var(--text-muted); flex: 1; line-height: 1.4; strong { color: var(--text-secondary); } }
    .ais-match {
      font-size: 0.65rem; font-weight: 700; padding: 0.15rem 0.45rem; border-radius: var(--radius-sm); white-space: nowrap;
      &.match { background: var(--status-confirm-bg); color: var(--status-confirm); }
      &.mismatch { background: var(--status-critical-bg); color: var(--status-critical); }
    }
    .collab-header {
      display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1rem;
      .collab-icon { font-size: 1.2rem; }
      .collab-title { font-size: 0.85rem; color: var(--accent-tertiary); font-weight: 600; }
    }
    .agent-hints-grid {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 0.75rem;
    }
    .agent-hint {
      background: var(--bg-glass); border-radius: var(--radius-md); padding: 0.75rem;
      border: 1px solid var(--border-subtle);
    }
    .hint-header {
      display: flex; align-items: center; gap: 0.4rem; margin-bottom: 0.4rem;
    }
    .hint-flag { font-size: 1.1rem; }
    .hint-region { font-size: 0.75rem; color: var(--text-secondary); font-weight: 600; flex: 1; }
    .hint-verdict {
      font-size: 0.6rem; font-weight: 700; padding: 0.15rem 0.4rem; border-radius: var(--radius-sm);
      &.v-ai { background: var(--label-ai-bg); color: var(--label-ai); }
      &.v-human { background: var(--label-human-bg); color: var(--label-human); }
    }
    .hint-conf { font-size: 0.65rem; color: var(--text-muted); }
    .hint-reasoning { margin: 0; font-size: 0.7rem; color: var(--text-muted); line-height: 1.5; }
    .hint-media, .agent-review-media {
      margin: 0.4rem 0;
      border-radius: var(--radius-sm);
      overflow: hidden;
    }
    .agent-media-img {
      width: 100%; height: auto; max-height: 160px; object-fit: cover;
      border-radius: var(--radius-sm);
    }
    .agent-media-video {
      width: 100%; max-height: 160px; border-radius: var(--radius-sm); background: #000;
    }
    .already-answered {
      display: flex; flex-direction: column; gap: 1rem;
    }
    .answer-summary {
      display: flex; align-items: center; gap: 1rem; padding: 1rem 1.5rem;
      border-radius: var(--radius-md);
      &.correct { background: var(--status-confirm-bg); border: 1px solid var(--status-confirm); }
      &.wrong { background: var(--status-critical-bg); border: 1px solid var(--status-critical); }
      .answer-icon { font-size: 1.5rem; }
      .answer-details {
        display: flex; flex-direction: column; gap: 0.2rem;
        span { font-size: 0.85rem; color: var(--text-secondary); }
      }
    }
    .post-answer-agents {
      h4 { margin: 0 0 0.75rem; color: var(--text-muted); font-size: 0.9rem; }
    }
    .agent-grid-review {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 0.6rem;
    }
    .agent-review-card {
      padding: 0.75rem; border-radius: var(--radius-md);
      border: 1px solid var(--border-subtle); background: var(--bg-glass);
      &.agent-correct { border-color: var(--status-confirm); }
      &.agent-wrong { border-color: var(--status-critical); }
    }
    .arc-header {
      display: flex; align-items: center; gap: 0.4rem; margin-bottom: 0.3rem;
      font-size: 0.78rem; color: var(--text-secondary); font-weight: 500;
    }
    .arc-verdict {
      font-size: 0.6rem; font-weight: 700; padding: 0.1rem 0.35rem; border-radius: 4px; margin-left: auto;
      &.v-ai { background: var(--label-ai-bg); color: var(--label-ai); }
      &.v-human { background: var(--label-human-bg); color: var(--label-human); }
    }
    .arc-result { font-size: 0.85rem; }
    .arc-conf { font-size: 0.65rem; color: var(--text-muted); margin-bottom: 0.2rem; }
    .arc-reasoning { margin: 0; font-size: 0.68rem; color: var(--text-muted); line-height: 1.4; }
    .verdict-input {
      background: var(--bg-secondary);
      border-radius: var(--radius-lg); padding: 2rem; border: 1px solid var(--border-subtle);
    }
    .verdict-question {
      margin: 0 0 1.5rem; color: var(--text-primary); font-size: 1.1rem; text-align: center;
    }
    .verdict-buttons {
      display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 1.5rem;
    }
    .verdict-btn {
      padding: 1.5rem; border-radius: var(--radius-md); cursor: pointer; text-align: center;
      border: 2px solid var(--border-default); background: var(--bg-glass);
      transition: all 0.3s; display: flex; flex-direction: column; align-items: center; gap: 0.5rem;
      min-height: var(--min-touch-target);
      .vb-icon { font-size: 2.5rem; }
      .vb-label { font-size: 1rem; color: var(--text-secondary); font-weight: 600; }
      &:hover { transform: translateY(-3px); background: var(--bg-elevated); }
      &.ai-btn.selected {
        border-color: var(--label-ai); background: var(--label-ai-bg);
        box-shadow: var(--shadow-lg);
        .vb-label { color: var(--label-ai); }
      }
      &.human-btn.selected {
        border-color: var(--label-human); background: var(--label-human-bg);
        box-shadow: var(--shadow-lg);
        .vb-label { color: var(--label-human); }
      }
    }
    .confidence-input {
      margin-bottom: 1.25rem;
      label { display: block; color: var(--text-muted); font-size: 0.85rem; margin-bottom: 0.5rem; }
    }
    .confidence-scale { display: flex; gap: 0.5rem; justify-content: center; margin-bottom: 0.3rem; }
    .conf-btn {
      width: 48px; height: 48px; border-radius: 50%; cursor: pointer;
      background: var(--bg-glass); border: 1px solid var(--border-default);
      color: var(--text-secondary); font-size: 1rem; font-weight: 600; transition: all 0.3s;
      min-height: var(--min-touch-target);
      &:hover { background: var(--bg-elevated); }
      &.selected {
        background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary)); color: var(--text-inverse);
        border-color: transparent; transform: scale(1.1);
      }
    }
    .conf-labels {
      display: flex; justify-content: space-between;
      span { font-size: 0.7rem; color: var(--text-muted); }
    }
    .reasoning-input {
      margin-bottom: 1.5rem;
      label { display: block; color: var(--text-muted); font-size: 0.85rem; margin-bottom: 0.5rem; }
      textarea {
        width: 100%; background: var(--bg-glass); border: 1px solid var(--border-default);
        border-radius: var(--radius-md); padding: 0.75rem; color: var(--text-secondary); font-size: 0.9rem;
        resize: vertical; font-family: inherit;
        &::placeholder { color: var(--text-muted); }
        &:focus { outline: none; border-color: var(--accent-primary); }
      }
    }
    .submit-btn {
      width: 100%; padding: 1rem; border: none; border-radius: var(--radius-md); cursor: pointer;
      background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary)); color: var(--text-inverse);
      font-size: 1rem; font-weight: 700; transition: all 0.3s; min-height: var(--min-touch-target);
      &:hover:not(:disabled) { transform: translateY(-2px); box-shadow: var(--shadow-lg); }
      &:disabled { opacity: 0.4; cursor: not-allowed; }
    }
    @media (forced-colors: active) {
      .config-btn, .start-btn, .submit-btn, .verdict-btn, .conf-btn { border: 2px solid ButtonText; }
      .progress-dot { border: 2px solid ButtonText; }
      .progress-dot.current { border-color: Highlight; }
    }
    @media (max-width: 600px) {
      .survey-container { padding: 1rem; }
      .verdict-buttons { grid-template-columns: 1fr; }
      .agent-hints-grid, .agent-grid-review { grid-template-columns: 1fr; }
      .info-cards { grid-template-columns: 1fr 1fr; }
    }
    /* Loading screen */
    .loading-screen {
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      min-height: 60vh; gap: 1.5rem; text-align: center;
      h2 { color: var(--text-primary); font-size: 1.5rem; margin: 0; }
      p { color: var(--text-muted); font-size: 0.95rem; margin: 0; }
    }
    .loading-spinner {
      width: 56px; height: 56px; border: 4px solid var(--border-default);
      border-top-color: var(--accent-primary); border-radius: 50%;
      animation: spin 1s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }
    .loading-sources {
      display: flex; gap: 0.5rem; flex-wrap: wrap; justify-content: center; margin-top: 0.5rem;
    }
    .source-tag {
      background: var(--bg-glass); border: 1px solid var(--border-default);
      padding: 0.35rem 0.75rem; border-radius: var(--radius-full); font-size: 0.75rem; color: var(--text-secondary);
    }
    /* Video support */
    .item-video-wrap {
      margin-top: 1rem; border-radius: var(--radius-md); overflow: hidden;
      background: var(--bg-primary);
    }
    .item-video {
      width: 100%; max-height: 400px; border-radius: var(--radius-md);
    }
  `]
})
export class SurveyComponent {
  surveyService = inject(SurveyService);
  private errorService = inject(ErrorNotificationService);

  selectedCount = 6;
  collabMode = false;

  pendingVerdict: 'ai' | 'human' | null = null;
  pendingConfidence: number | null = null;
  pendingReasoning = '';
  honeypot = ''; // Bot detection: hidden field that real users never fill
  itemShownAt = Date.now(); // Response time tracking

  private regionFlags: Record<string, string> = {
    'Africa': '🌍', 'Asia': '🌏', 'Europe': '🇪🇺', 'North_America': '🌎', 'South_America': '🌎', 'Antarctica': '🧊', 'Australia': '🦘',
  };

  async startSurvey(): Promise<void> {
    try {
      await this.surveyService.startSession(this.collabMode);
      this.itemShownAt = Date.now(); // Start timing first item
    } catch (err) {
      console.error('Survey failed to start:', err);
      this.errorService.notify('error',
        'Unable to start survey',
        'Something unexpected happened while preparing your survey session. This is not something you did wrong.',
        {
          suggestion: 'Please try again. If the problem continues, the survey may be temporarily unavailable.',
          context: 'survey-start',
          recoverable: true,
          retryAction: () => this.startSurvey(),
        }
      );
    }
  }

  getRegionFlag(region: string): string {
    return this.regionFlags[region] ?? '🌐';
  }

  isLastItem(): boolean {
    const s = this.surveyService.session();
    return s ? s.currentIndex === s.items.length - 1 : false;
  }

  submitAnswer(): void {
    if (!this.pendingVerdict || !this.pendingConfidence) return;

    // Honeypot check: if filled, silently reject (bot detected)
    if (this.honeypot) {
      console.warn('Bot detected via honeypot');
      this.pendingVerdict = null;
      this.pendingConfidence = null;
      this.pendingReasoning = '';
      return;
    }

    // Response time check: flag if answered too fast (<2 seconds)
    const now = Date.now();
    const elapsed = now - this.itemShownAt;
    const isSuspiciouslyFast = elapsed < 2000;

    this.surveyService.submitVerdict(
      this.pendingVerdict, this.pendingConfidence, this.pendingReasoning,
      { responseTimeMs: elapsed, flaggedFast: isSuspiciouslyFast }
    );
    this.pendingVerdict = null;
    this.pendingConfidence = null;
    this.pendingReasoning = '';
    this.itemShownAt = Date.now(); // Reset for next item
  }

  getAgentConsensus(verdicts: { verdict: string }[]): boolean {
    if (!verdicts || verdicts.length === 0) return false;
    const aiCount = verdicts.filter(v => v.verdict === 'ai').length;
    return aiCount >= 5 || aiCount <= 2; // 5+ agree or 5+ agree on human
  }

  getMajorityVerdict(verdicts: { verdict: string }[]): string {
    if (!verdicts || verdicts.length === 0) return 'unknown';
    const aiCount = verdicts.filter(v => v.verdict === 'ai').length;
    return aiCount > verdicts.length / 2 ? 'ai' : 'human';
  }
}
