import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SurveyService } from '../../services/survey.service';
import { SurveyResultsComponent } from '../survey-results/survey-results.component';
import { ErrorNotificationService } from '../../services/error-notification.service';

@Component({
  selector: 'app-survey',
  standalone: true,
  imports: [CommonModule, FormsModule, SurveyResultsComponent],
  template: `
    <!-- Survey Landing / Start Screen -->
    <div class="survey-container" *ngIf="!surveyService.isActive() && !surveyService.isComplete() && !surveyService.loading()">
      <div class="survey-landing">
        <div class="landing-header">
          <span class="landing-icon">📋</span>
          <h1>Human-in-the-Loop AI Research Survey</h1>
          <p class="landing-subtitle">Data Authenticity Assessment — Can you tell AI from Human?</p>
        </div>

        <div class="landing-description">
          <div class="research-badge">
            <span class="rb-icon">🔬</span>
            <span>Research Protocol</span>
          </div>
          <p>
            This survey is part of a research study on <strong>Human-AI Collaboration</strong> for data authenticity.
            You will be shown content from the TrustFeed platform and asked to determine whether each item was
            created by a human or generated by AI. Five continental AI bias agents will independently analyze the
            same content — your results will be compared with theirs.
          </p>

          <div class="info-cards">
            <div class="info-card">
              <span class="ic-icon">🎯</span>
              <h4>Your Task</h4>
              <p>Read each content item carefully and decide: AI-generated or human-created?</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">🌍</span>
              <h4>5 AI Agents</h4>
              <p>Africa, Asia, Europe, Americas & Oceania agents each give unique verdicts</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">🤝</span>
              <h4>Human-AI Collab</h4>
              <p>Optional: see agent hints while you answer to study collaboration effects</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">📊</span>
              <h4>Results Dashboard</h4>
              <p>Compare your accuracy vs. each AI agent after completing the survey</p>
            </div>
          </div>
        </div>

        <div class="survey-config">
          <h3>Configure Your Session</h3>
          <div class="config-row">
            <label>Number of Items</label>
            <div class="config-options">
              <button *ngFor="let n of itemCounts"
                [class.active]="selectedCount === n"
                (click)="selectedCount = n"
                class="config-btn">{{ n }}</button>
            </div>
          </div>
          <div class="config-row">
            <label>Mode</label>
            <div class="config-options">
              <button [class.active]="!collabMode" (click)="collabMode = false" class="config-btn mode-btn">
                <span>👤</span> Solo (Human Only)
              </button>
              <button [class.active]="collabMode" (click)="collabMode = true" class="config-btn mode-btn collab">
                <span>🤝</span> Human-AI Collab
              </button>
            </div>
          </div>
          <p class="collab-note" *ngIf="collabMode">
            In <strong>Human-AI Collab</strong> mode, you'll see agent verdicts <em>before</em> making your decision.
            This measures how AI assistance affects human judgment accuracy.
          </p>
          <button class="start-btn" (click)="startSurvey()">
            <span>🚀</span> Begin Research Survey
          </button>
        </div>

        <div class="consent-notice">
          <span class="consent-icon">🔒</span>
          <p>You have provided informed consent. No personal data is collected or transmitted.</p>
        </div>
      </div>
    </div>

    <!-- Loading Screen — Fetching unique content from internet -->
    <div class="survey-container" *ngIf="surveyService.loading()">
      <div class="loading-screen">
        <div class="loading-spinner"></div>
        <h2>Fetching Unique Content</h2>
        <p>Loading fresh images, videos, and text from free internet sources...</p>
        <div class="loading-sources">
          <span class="source-tag">📖 Wikipedia</span>
          <span class="source-tag">📸 Picsum Photos</span>
          <span class="source-tag">🎨 Pollinations AI</span>
          <span class="source-tag">🎬 Pexels Videos</span>
        </div>
      </div>
    </div>

    <!-- Active Survey -->
    <div class="survey-container" *ngIf="surveyService.isActive()">
      <div class="survey-progress">
        <div class="progress-info">
          <span class="progress-label">Progress</span>
          <span class="progress-count">{{ surveyService.progress().current }} / {{ surveyService.progress().total }}</span>
        </div>
        <div class="progress-bar">
          <div class="progress-fill" [style.width.%]="surveyService.progress().percent"></div>
        </div>
        <div class="progress-items">
          <button *ngFor="let item of surveyService.session()!.items; let i = index"
            class="progress-dot"
            [class.answered]="item.humanVerdict != null"
            [class.current]="i === surveyService.session()!.currentIndex"
            [class.correct]="item.humanVerdict != null && item.humanVerdict === item.groundTruth"
            [class.wrong]="item.humanVerdict != null && item.humanVerdict !== item.groundTruth"
            (click)="surveyService.goToItem(i)">
            {{ i + 1 }}
          </button>
        </div>
      </div>

      <!-- Current Item -->
      <div class="survey-item" *ngIf="surveyService.currentItem() as item">
        <div class="item-header">
          <span class="item-number">Item {{ surveyService.session()!.currentIndex + 1 }}</span>
          <span class="item-category">{{ item.category }}</span>
          <span class="item-difficulty" [class]="'diff-' + item.difficulty">{{ item.difficulty }}</span>
          <span class="item-type">{{ item.contentType }}</span>
        </div>

        <div class="item-content-card">
          <h3 class="item-title">{{ item.title }}</h3>
          <p class="item-content">{{ item.content }}</p>
          <img *ngIf="item.imageUrl && item.contentType !== 'video'" [src]="item.imageUrl" alt="Survey content image" class="item-image" />
          <div class="item-video-wrap" *ngIf="item.contentType === 'video' && item.videoUrl">
            <video controls [poster]="item.imageUrl || ''" class="item-video">
              <source [src]="item.videoUrl" type="video/mp4">
              Your browser does not support video playback.
            </video>
          </div>
          <img *ngIf="item.contentType === 'video' && !item.videoUrl && item.imageUrl" [src]="item.imageUrl" alt="Video thumbnail" class="item-image" />
        </div>

        <!-- Human-AI Collab: Agent Hints (shown before answering in collab mode) -->
        <div class="collab-hints" *ngIf="surveyService.session()!.collabMode && item.humanVerdict == null">
          <div class="collab-header">
            <span class="collab-icon">🤝</span>
            <span class="collab-title">Human-AI Collaboration Mode — Agent Hints</span>
          </div>
          <div class="agent-hints-grid">
            <div class="agent-hint" *ngFor="let av of item.agentVerdicts">
              <div class="hint-header">
                <span class="hint-flag">{{ getRegionFlag(av.region) }}</span>
                <span class="hint-region">{{ av.region }}</span>
                <span class="hint-verdict" [class]="'v-' + av.verdict">{{ av.verdict | uppercase }}</span>
                <span class="hint-conf">{{ av.confidence * 100 | number:'1.0-0' }}%</span>
              </div>
              <div class="hint-media" *ngIf="av.analysisImageUrl || av.analysisVideoUrl">
                <video *ngIf="av.analysisMediaType === 'video' && av.analysisVideoUrl" [src]="av.analysisVideoUrl" [poster]="av.analysisImageUrl" controls muted class="agent-media-video"></video>
                <img *ngIf="av.analysisMediaType === 'image' && av.analysisImageUrl" [src]="av.analysisImageUrl" alt="Agent analysis media" class="agent-media-img" loading="lazy" />
              </div>
              <p class="hint-reasoning">{{ av.reasoning }}</p>
            </div>
          </div>
        </div>

        <!-- Already-answered review -->
        <div class="already-answered" *ngIf="item.humanVerdict != null">
          <div class="answer-summary" [class.correct]="item.humanVerdict === item.groundTruth" [class.wrong]="item.humanVerdict !== item.groundTruth">
            <span class="answer-icon">{{ item.humanVerdict === item.groundTruth ? '✅' : '❌' }}</span>
            <div class="answer-details">
              <span>Your answer: <strong>{{ item.humanVerdict | uppercase }}</strong></span>
              <span>Truth: <strong>{{ item.groundTruth | uppercase }}</strong></span>
            </div>
          </div>
          <!-- Show all agent verdicts after answering -->
          <div class="post-answer-agents">
            <h4>🌍 Agent Verdicts</h4>
            <div class="agent-grid-review">
              <div class="agent-review-card" *ngFor="let av of item.agentVerdicts"
                [class.agent-correct]="av.verdict === item.groundTruth"
                [class.agent-wrong]="av.verdict !== item.groundTruth">
                <div class="arc-header">
                  <span>{{ getRegionFlag(av.region) }} {{ av.region }}</span>
                  <span class="arc-verdict" [class]="'v-' + av.verdict">{{ av.verdict | uppercase }}</span>
                  <span class="arc-result">{{ av.verdict === item.groundTruth ? '✅' : '❌' }}</span>
                </div>
                <div class="arc-conf">Confidence: {{ av.confidence * 100 | number:'1.0-0' }}%</div>
                <p class="arc-reasoning">{{ av.reasoning }}</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Verdict Input (only show if not yet answered) -->
        <div class="verdict-input" *ngIf="item.humanVerdict == null">
          <h3 class="verdict-question">Is this content AI-generated or human-created?</h3>

          <div class="verdict-buttons">
            <button class="verdict-btn ai-btn" [class.selected]="pendingVerdict === 'ai'" (click)="pendingVerdict = 'ai'">
              <span class="vb-icon">🤖</span>
              <span class="vb-label">AI Generated</span>
            </button>
            <button class="verdict-btn human-btn" [class.selected]="pendingVerdict === 'human'" (click)="pendingVerdict = 'human'">
              <span class="vb-icon">👤</span>
              <span class="vb-label">Human Created</span>
            </button>
          </div>

          <div class="confidence-input" *ngIf="pendingVerdict">
            <label>Confidence Level</label>
            <div class="confidence-scale">
              <button *ngFor="let c of [1,2,3,4,5]"
                class="conf-btn"
                [class.selected]="pendingConfidence === c"
                (click)="pendingConfidence = c">
                {{ c }}
              </button>
            </div>
            <div class="conf-labels">
              <span>Not sure</span>
              <span>Very confident</span>
            </div>
          </div>

          <div class="reasoning-input" *ngIf="pendingVerdict">
            <label>Why do you think so? (optional)</label>
            <textarea [(ngModel)]="pendingReasoning" placeholder="Describe what clues led to your decision..." rows="3"></textarea>
          </div>

          <button class="submit-btn" [disabled]="!pendingVerdict || !pendingConfidence" (click)="submitAnswer()">
            {{ isLastItem() ? '✅ Submit & View Results' : '➡️ Submit & Next' }}
          </button>
        </div>
      </div>
    </div>

    <!-- Results Dashboard -->
    <app-survey-results *ngIf="surveyService.isComplete()" />
  `,
  styles: [`
    .survey-container {
      max-width: 900px;
      margin: 0 auto;
      padding: 2rem;
    }
    .survey-landing {
      display: flex;
      flex-direction: column;
      gap: 2rem;
    }
    .landing-header {
      text-align: center;
      .landing-icon { font-size: 3rem; display: block; margin-bottom: 1rem; }
      h1 { margin: 0 0 0.5rem; font-size: 2rem; color: #e6e6e6; font-weight: 700; }
      .landing-subtitle { color: #8892b0; font-size: 1.1rem; margin: 0; }
    }
    .landing-description {
      background: linear-gradient(145deg, #1e1e2e, #252538);
      border-radius: 16px; padding: 2rem; border: 1px solid rgba(255,255,255,0.05);
      p { color: #ccd6f6; line-height: 1.8; font-size: 0.95rem; margin: 1rem 0 1.5rem; }
    }
    .research-badge {
      display: inline-flex; align-items: center; gap: 0.5rem;
      background: rgba(0,217,255,0.08); border: 1px solid rgba(0,217,255,0.2);
      padding: 0.4rem 1rem; border-radius: 20px; color: #00d9ff;
      font-size: 0.8rem; font-weight: 600;
      .rb-icon { font-size: 1rem; }
    }
    .info-cards {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem;
    }
    .info-card {
      background: rgba(255,255,255,0.03); border-radius: 12px; padding: 1.25rem;
      border: 1px solid rgba(255,255,255,0.05); text-align: center;
      .ic-icon { font-size: 2rem; display: block; margin-bottom: 0.5rem; }
      h4 { margin: 0 0 0.4rem; color: #e6e6e6; font-size: 0.9rem; }
      p { margin: 0; color: #8892b0; font-size: 0.75rem; line-height: 1.5; }
    }
    .survey-config {
      background: linear-gradient(145deg, #1e1e2e, #252538);
      border-radius: 16px; padding: 2rem; border: 1px solid rgba(255,255,255,0.05);
      h3 { margin: 0 0 1.5rem; color: #e6e6e6; font-size: 1.1rem; }
    }
    .config-row {
      margin-bottom: 1.25rem;
      label { display: block; color: #8892b0; font-size: 0.85rem; margin-bottom: 0.5rem; font-weight: 500; }
    }
    .config-options { display: flex; gap: 0.5rem; flex-wrap: wrap; }
    .config-btn {
      background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1);
      color: #ccd6f6; padding: 0.6rem 1.25rem; border-radius: 10px; cursor: pointer;
      font-size: 0.9rem; transition: all 0.3s;
      &:hover { background: rgba(255,255,255,0.1); }
      &.active {
        background: linear-gradient(135deg, #00d9ff, #00ff88); color: #0a0a0f;
        font-weight: 600; border-color: transparent;
      }
    }
    .mode-btn {
      display: flex; align-items: center; gap: 0.5rem;
      &.collab.active { background: linear-gradient(135deg, #9c27b0, #e91e63); color: white; }
    }
    .collab-note {
      background: rgba(156,39,176,0.08); border: 1px solid rgba(156,39,176,0.2);
      padding: 0.75rem 1rem; border-radius: 10px; font-size: 0.82rem;
      color: #ce93d8; margin: 0.5rem 0 1rem; line-height: 1.5;
    }
    .start-btn {
      width: 100%; padding: 1rem; border: none; border-radius: 12px; cursor: pointer;
      background: linear-gradient(135deg, #00d9ff, #00ff88); color: #0a0a0f;
      font-size: 1.1rem; font-weight: 700; display: flex; align-items: center;
      justify-content: center; gap: 0.5rem; transition: all 0.3s;
      &:hover { transform: translateY(-2px); box-shadow: 0 8px 25px rgba(0,217,255,0.3); }
    }
    .consent-notice {
      display: flex; align-items: flex-start; gap: 0.75rem;
      background: rgba(255,255,255,0.02); border-radius: 12px; padding: 1rem 1.5rem;
      border: 1px solid rgba(255,255,255,0.05);
      .consent-icon { font-size: 1.25rem; flex-shrink: 0; margin-top: 2px; }
      p { margin: 0; color: #8892b0; font-size: 0.78rem; line-height: 1.6; }
    }
    .survey-progress {
      background: linear-gradient(145deg, #1e1e2e, #252538);
      border-radius: 16px; padding: 1.25rem 1.5rem; margin-bottom: 1.5rem;
      border: 1px solid rgba(255,255,255,0.05);
    }
    .progress-info {
      display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem;
    }
    .progress-label { font-size: 0.8rem; color: #8892b0; }
    .progress-count { font-size: 0.85rem; color: #00d9ff; font-weight: 600; }
    .progress-bar {
      height: 6px; background: rgba(255,255,255,0.08); border-radius: 3px; overflow: hidden;
      margin-bottom: 0.75rem;
    }
    .progress-fill {
      height: 100%; background: linear-gradient(90deg, #00d9ff, #00ff88);
      border-radius: 3px; transition: width 0.4s;
    }
    .progress-items { display: flex; gap: 0.35rem; flex-wrap: wrap; }
    .progress-dot {
      width: 28px; height: 28px; border-radius: 50%; border: 1px solid rgba(255,255,255,0.1);
      background: rgba(255,255,255,0.03); color: #8892b0; font-size: 0.65rem;
      cursor: pointer; display: flex; align-items: center; justify-content: center;
      transition: all 0.2s;
      &.current { border-color: #00d9ff; color: #00d9ff; background: rgba(0,217,255,0.1); }
      &.answered { border-color: rgba(0,255,136,0.3); }
      &.correct { background: rgba(76,175,80,0.15); color: #4caf50; border-color: rgba(76,175,80,0.3); }
      &.wrong { background: rgba(244,67,54,0.12); color: #f44336; border-color: rgba(244,67,54,0.3); }
    }
    .survey-item {
      display: flex; flex-direction: column; gap: 1.25rem;
    }
    .item-header {
      display: flex; align-items: center; gap: 0.75rem; flex-wrap: wrap;
    }
    .item-number {
      font-size: 0.85rem; color: #00d9ff; font-weight: 600;
      background: rgba(0,217,255,0.08); padding: 0.3rem 0.75rem; border-radius: 8px;
    }
    .item-category {
      font-size: 0.75rem; color: #ccd6f6; background: rgba(255,255,255,0.05);
      padding: 0.2rem 0.6rem; border-radius: 6px;
    }
    .item-difficulty {
      font-size: 0.65rem; font-weight: 700; padding: 0.2rem 0.5rem; border-radius: 6px;
      text-transform: uppercase; letter-spacing: 0.5px;
      &.diff-easy { background: rgba(76,175,80,0.15); color: #4caf50; }
      &.diff-medium { background: rgba(255,152,0,0.15); color: #ff9800; }
      &.diff-hard { background: rgba(244,67,54,0.15); color: #f44336; }
    }
    .item-type {
      font-size: 0.65rem; color: #8892b0; background: rgba(255,255,255,0.03);
      padding: 0.2rem 0.5rem; border-radius: 6px;
    }
    .item-content-card {
      background: linear-gradient(145deg, #1e1e2e, #252538);
      border-radius: 16px; padding: 2rem; border: 1px solid rgba(255,255,255,0.05);
    }
    .item-title {
      margin: 0 0 1rem; color: #e6e6e6; font-size: 1.2rem; font-weight: 600;
    }
    .item-content {
      margin: 0; color: #ccd6f6; font-size: 1rem; line-height: 1.8;
    }
    .item-image {
      width: 100%; border-radius: 12px; margin-top: 1rem; max-height: 400px; object-fit: cover;
    }
    .collab-hints {
      background: linear-gradient(135deg, rgba(156,39,176,0.06), rgba(0,217,255,0.04));
      border-radius: 14px; padding: 1.25rem; border: 1px solid rgba(156,39,176,0.15);
    }
    .collab-header {
      display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1rem;
      .collab-icon { font-size: 1.2rem; }
      .collab-title { font-size: 0.85rem; color: #ce93d8; font-weight: 600; }
    }
    .agent-hints-grid {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 0.75rem;
    }
    .agent-hint {
      background: rgba(255,255,255,0.03); border-radius: 10px; padding: 0.75rem;
      border: 1px solid rgba(255,255,255,0.05);
    }
    .hint-header {
      display: flex; align-items: center; gap: 0.4rem; margin-bottom: 0.4rem;
    }
    .hint-flag { font-size: 1.1rem; }
    .hint-region { font-size: 0.75rem; color: #ccd6f6; font-weight: 600; flex: 1; }
    .hint-verdict {
      font-size: 0.6rem; font-weight: 700; padding: 0.15rem 0.4rem; border-radius: 6px;
      &.v-ai { background: rgba(233,30,99,0.15); color: #e91e63; }
      &.v-human { background: rgba(76,175,80,0.15); color: #4caf50; }
    }
    .hint-conf { font-size: 0.65rem; color: #8892b0; }
    .hint-reasoning { margin: 0; font-size: 0.7rem; color: #8892b0; line-height: 1.5; }
    .already-answered {
      display: flex; flex-direction: column; gap: 1rem;
    }
    .answer-summary {
      display: flex; align-items: center; gap: 1rem; padding: 1rem 1.5rem;
      border-radius: 12px;
      &.correct { background: rgba(76,175,80,0.1); border: 1px solid rgba(76,175,80,0.2); }
      &.wrong { background: rgba(244,67,54,0.08); border: 1px solid rgba(244,67,54,0.2); }
      .answer-icon { font-size: 1.5rem; }
      .answer-details {
        display: flex; flex-direction: column; gap: 0.2rem;
        span { font-size: 0.85rem; color: #ccd6f6; }
      }
    }
    .post-answer-agents {
      h4 { margin: 0 0 0.75rem; color: #8892b0; font-size: 0.9rem; }
    }
    .agent-grid-review {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 0.6rem;
    }
    .agent-review-card {
      padding: 0.75rem; border-radius: 10px;
      border: 1px solid rgba(255,255,255,0.05); background: rgba(255,255,255,0.02);
      &.agent-correct { border-color: rgba(76,175,80,0.2); }
      &.agent-wrong { border-color: rgba(244,67,54,0.15); }
    }
    .arc-header {
      display: flex; align-items: center; gap: 0.4rem; margin-bottom: 0.3rem;
      font-size: 0.78rem; color: #ccd6f6; font-weight: 500;
    }
    .arc-verdict {
      font-size: 0.6rem; font-weight: 700; padding: 0.1rem 0.35rem; border-radius: 4px; margin-left: auto;
      &.v-ai { background: rgba(233,30,99,0.15); color: #e91e63; }
      &.v-human { background: rgba(76,175,80,0.15); color: #4caf50; }
    }
    .arc-result { font-size: 0.85rem; }
    .arc-conf { font-size: 0.65rem; color: #8892b0; margin-bottom: 0.2rem; }
    .arc-reasoning { margin: 0; font-size: 0.68rem; color: #8892b0; line-height: 1.4; }
    .verdict-input {
      background: linear-gradient(145deg, #1e1e2e, #252538);
      border-radius: 16px; padding: 2rem; border: 1px solid rgba(255,255,255,0.05);
    }
    .verdict-question {
      margin: 0 0 1.5rem; color: #e6e6e6; font-size: 1.1rem; text-align: center;
    }
    .verdict-buttons {
      display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 1.5rem;
    }
    .verdict-btn {
      padding: 1.5rem; border-radius: 14px; cursor: pointer; text-align: center;
      border: 2px solid rgba(255,255,255,0.1); background: rgba(255,255,255,0.03);
      transition: all 0.3s; display: flex; flex-direction: column; align-items: center; gap: 0.5rem;
      .vb-icon { font-size: 2.5rem; }
      .vb-label { font-size: 1rem; color: #ccd6f6; font-weight: 600; }
      &:hover { transform: translateY(-3px); background: rgba(255,255,255,0.06); }
      &.ai-btn.selected {
        border-color: #e91e63; background: rgba(233,30,99,0.1);
        box-shadow: 0 8px 25px rgba(233,30,99,0.2);
        .vb-label { color: #e91e63; }
      }
      &.human-btn.selected {
        border-color: #4caf50; background: rgba(76,175,80,0.1);
        box-shadow: 0 8px 25px rgba(76,175,80,0.2);
        .vb-label { color: #4caf50; }
      }
    }
    .confidence-input {
      margin-bottom: 1.25rem;
      label { display: block; color: #8892b0; font-size: 0.85rem; margin-bottom: 0.5rem; }
    }
    .confidence-scale { display: flex; gap: 0.5rem; justify-content: center; margin-bottom: 0.3rem; }
    .conf-btn {
      width: 48px; height: 48px; border-radius: 50%; cursor: pointer;
      background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1);
      color: #ccd6f6; font-size: 1rem; font-weight: 600; transition: all 0.3s;
      &:hover { background: rgba(255,255,255,0.1); }
      &.selected {
        background: linear-gradient(135deg, #00d9ff, #00ff88); color: #0a0a0f;
        border-color: transparent; transform: scale(1.1);
      }
    }
    .conf-labels {
      display: flex; justify-content: space-between;
      span { font-size: 0.7rem; color: #5a6480; }
    }
    .reasoning-input {
      margin-bottom: 1.5rem;
      label { display: block; color: #8892b0; font-size: 0.85rem; margin-bottom: 0.5rem; }
      textarea {
        width: 100%; background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1);
        border-radius: 10px; padding: 0.75rem; color: #ccd6f6; font-size: 0.9rem;
        resize: vertical; font-family: inherit;
        &::placeholder { color: #5a6480; }
        &:focus { outline: none; border-color: rgba(0,217,255,0.3); }
      }
    }
    .submit-btn {
      width: 100%; padding: 1rem; border: none; border-radius: 12px; cursor: pointer;
      background: linear-gradient(135deg, #00d9ff, #00ff88); color: #0a0a0f;
      font-size: 1rem; font-weight: 700; transition: all 0.3s;
      &:hover:not(:disabled) { transform: translateY(-2px); box-shadow: 0 8px 25px rgba(0,217,255,0.3); }
      &:disabled { opacity: 0.4; cursor: not-allowed; }
    }
    @media (max-width: 600px) {
      .survey-container { padding: 1rem; }
      .verdict-buttons { grid-template-columns: 1fr; }
      .agent-hints-grid, .agent-grid-review { grid-template-columns: 1fr; }
      .info-cards { grid-template-columns: 1fr 1fr; }
    }
    /* Loading screen */
    .loading-screen {
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      min-height: 60vh; gap: 1.5rem; text-align: center;
      h2 { color: #e6e6e6; font-size: 1.5rem; margin: 0; }
      p { color: #8892b0; font-size: 0.95rem; margin: 0; }
    }
    .loading-spinner {
      width: 56px; height: 56px; border: 4px solid rgba(255,255,255,0.08);
      border-top-color: #00d9ff; border-radius: 50%;
      animation: spin 1s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }
    .loading-sources {
      display: flex; gap: 0.5rem; flex-wrap: wrap; justify-content: center; margin-top: 0.5rem;
    }
    .source-tag {
      background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1);
      padding: 0.35rem 0.75rem; border-radius: 20px; font-size: 0.75rem; color: #ccd6f6;
    }
    /* Video support */
    .item-video-wrap {
      margin-top: 1rem; border-radius: 12px; overflow: hidden;
      background: rgba(0,0,0,0.3);
    }
    .item-video {
      width: 100%; max-height: 400px; border-radius: 12px;
    }
  `]
})
export class SurveyComponent {
  surveyService = inject(SurveyService);
  private errorService = inject(ErrorNotificationService);

  selectedCount = 10;
  collabMode = false;
  itemCounts = [5, 8, 10, 12, 16];

  pendingVerdict: 'ai' | 'human' | null = null;
  pendingConfidence: number | null = null;
  pendingReasoning = '';

  private regionFlags: Record<string, string> = {
    'Africa': '🌍', 'Asia': '🌏', 'Europe': '🇪🇺', 'Americas': '🌎', 'Oceania': '🏝️',
  };

  async startSurvey(): Promise<void> {
    try {
      await this.surveyService.startSession(this.selectedCount, this.collabMode);
    } catch (err) {
      console.error('Survey failed to start:', err);
      this.errorService.notify('error',
        'Unable to start survey',
        'Something unexpected happened while preparing your survey session. This is not something you did wrong.',
        {
          suggestion: 'Please try again. If the problem continues, the survey may be temporarily unavailable.',
          context: 'survey-start',
          recoverable: true,
          retryAction: () => this.startSurvey(),
        }
      );
    }
  }

  getRegionFlag(region: string): string {
    return this.regionFlags[region] ?? '🌐';
  }

  isLastItem(): boolean {
    const s = this.surveyService.session();
    return s ? s.currentIndex === s.items.length - 1 : false;
  }

  submitAnswer(): void {
    if (!this.pendingVerdict || !this.pendingConfidence) return;
    this.surveyService.submitVerdict(this.pendingVerdict, this.pendingConfidence, this.pendingReasoning);
    this.pendingVerdict = null;
    this.pendingConfidence = null;
    this.pendingReasoning = '';
  }
}
