import { Component, inject, signal } from '@angular/core';
import { DecimalPipe, UpperCasePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SurveyService } from '../../services/survey.service';
import { SurveyResultsComponent } from '../survey-results/survey-results.component';
import { ImgFallbackDirective } from '../../utils/img-fallback.directive';

@Component({
  selector: 'app-survey',
  standalone: true,
  imports: [FormsModule, SurveyResultsComponent, DecimalPipe, UpperCasePipe, ImgFallbackDirective],
  template: `
    <!-- Survey Landing / Start Screen -->
    @if (!surveyService.isActive() && !surveyService.isComplete()) {
    <div class="survey-container">
      <div class="survey-landing">
        <div class="landing-header">
          <span class="landing-icon">📋</span>
          <h1>Human-in-the-Loop AI Research Survey</h1>
          <p class="landing-subtitle">Data Authenticity Assessment — Can you tell AI from Human?</p>
        </div>

        <div class="landing-description">
          <div class="research-badge">
            <span class="rb-icon">🔬</span>
            <span>Research Protocol</span>
          </div>
          <p>
            This survey is part of a research study on <strong>Human-AI Collaboration</strong> for data authenticity.
            You will be shown content from the TrustFeed platform and asked to determine whether each item was
            created by a human or generated by AI. Five continental AI bias agents will independently analyze the
            same content — your results will be compared with theirs.
          </p>

          <div class="info-cards">
            <div class="info-card">
              <span class="ic-icon">🎯</span>
              <h4>Your Task</h4>
              <p>Read each content item carefully and decide: AI-generated or human-created?</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">🌍</span>
              <h4>5 Regional Agents</h4>
              <p>Africa, Asia, Europe, Americas, and Oceania agents each provide region-aware verdicts</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">🤝</span>
              <h4>Human-AI Collab</h4>
              <p>Optional: see agent hints while you answer to study collaboration effects</p>
            </div>
            <div class="info-card">
              <span class="ic-icon">📊</span>
              <h4>Results Dashboard</h4>
              <p>Compare your accuracy vs. each AI agent after completing the survey</p>
            </div>
          </div>
        </div>

        <div class="survey-config">
          <h3>Start Your Session</h3>
          <div class="config-row">
            <label>Number of Items</label>
            <div class="config-options">
              @for (n of itemCounts; track $index) {
              <button
                [class.active]="selectedCount === n"
                (click)="selectedCount = n"
                class="config-btn">{{ n }}</button>
              }
            </div>
          </div>
          <div class="config-row">
            <label>Mode</label>
            <div class="config-options">
              <button [class.active]="!collabMode" (click)="collabMode = false" class="config-btn mode-btn">
                <span>👤</span> Solo (Human Only)
              </button>
              <button [class.active]="collabMode" (click)="collabMode = true" class="config-btn mode-btn collab">
                <span>🤝</span> Human-AI Collab
              </button>
            </div>
          </div>
          @if (collabMode) {
          <p class="collab-note">
            In <strong>Human-AI Collab</strong> mode, you'll see agent verdicts <em>before</em> making your decision.
            This measures how AI assistance affects human judgment accuracy.
          </p>
          }
          <button class="start-btn" (click)="startSurvey()">
            <span>🚀</span> Begin Research Survey
          </button>
        </div>

        <div class="consent-notice">
          <span class="consent-icon">🔒</span>
          <p>By starting, you acknowledge this is a research prototype for studying human-AI interaction
          in data authenticity assessment. No personal data is collected or transmitted.</p>
        </div>
      </div>
    </div>
    }

    <!-- Active Survey -->
    @if (surveyService.isActive()) {
    @let session = surveyService.session();
    @if (session) {
    <div class="survey-container">
      <div class="survey-progress">
        <div class="progress-info">
          <span class="progress-label">Progress</span>
          <span class="progress-count">{{ surveyService.progress().current }} / {{ surveyService.progress().total }}</span>
        </div>
        <div class="progress-bar">
          <div class="progress-fill" [style.width.%]="surveyService.progress().percent"></div>
        </div>
        <div class="progress-items">
          @for (item of session.items; track $index) {
          <button
            class="progress-dot"
            [class.answered]="item.humanVerdict != null"
            [class.current]="$index === session.currentIndex"
            [class.correct]="item.humanVerdict != null && item.humanVerdict === item.groundTruth"
            [class.wrong]="item.humanVerdict != null && item.humanVerdict !== item.groundTruth"
            (click)="surveyService.goToItem($index)">
            {{ $index + 1 }}
          </button>
          }
        </div>
      </div>

      <!-- Current Item -->
      @let item = surveyService.currentItem();
      @if (item) {
      <div class="survey-item">
        <div class="item-header">
          <span class="item-number">Item {{ session.currentIndex + 1 }}</span>
          <span class="item-category">{{ item.category }}</span>
          <span class="item-difficulty" [class]="'diff-' + item.difficulty">{{ item.difficulty }}</span>
          <span class="item-type">{{ item.contentType }}</span>
        </div>

        <div class="item-content-card">
          <h3 class="item-title">{{ item.title }}</h3>
          <p class="item-content">{{ item.content }}</p>
          @if (item.imageUrl) {
          <img [src]="item.imageUrl" alt="Survey content image" class="item-image" appImgFallback="survey-item" />
          }
        </div>

        <!-- Human-AI Collab: Agent Hints (shown before answering in collab mode) -->
        @if (session.collabMode && item.humanVerdict == null) {
        <div class="collab-hints">
          <div class="collab-header">
            <span class="collab-icon">🤝</span>
            <span class="collab-title">Human-AI Collaboration Mode — Agent Hints</span>
          </div>
          <div class="agent-hints-grid">
            @for (av of item.agentVerdicts; track $index) {
            <div class="agent-hint">
              <div class="hint-header">
                <span class="hint-flag">{{ getRegionFlag(av.region) }}</span>
                <span class="hint-region">{{ getDisplayRegion(av.region) }}</span>
                <span class="hint-verdict" [class]="'v-' + av.verdict">{{ av.verdict | uppercase }}</span>
                <span class="hint-conf">{{ av.confidence * 100 | number:'1.0-0' }}%</span>
              </div>
              <p class="hint-reasoning">{{ av.reasoning }}</p>
            </div>
            }
          </div>
        </div>
        }

        <!-- Already-answered review -->
        @if (item.humanVerdict != null) {
        <div class="already-answered">
          <div class="answer-summary" [class.correct]="item.humanVerdict === item.groundTruth" [class.wrong]="item.humanVerdict !== item.groundTruth">
            <span class="answer-icon">{{ item.humanVerdict === item.groundTruth ? '✅' : '❌' }}</span>
            <div class="answer-details">
              <span>Your answer: <strong>{{ item.humanVerdict | uppercase }}</strong></span>
              <span>Truth: <strong>{{ item.groundTruth | uppercase }}</strong></span>
            </div>
          </div>
          <!-- Show all agent verdicts after answering -->
          <div class="post-answer-agents">
            <h4>🌍 Agent Verdicts</h4>
            <div class="agent-grid-review">
              @for (av of item.agentVerdicts; track $index) {
              <div class="agent-review-card"
                [class.agent-correct]="av.verdict === item.groundTruth"
                [class.agent-wrong]="av.verdict !== item.groundTruth">
                <div class="arc-header">
                  <span>{{ getRegionFlag(av.region) }} {{ getDisplayRegion(av.region) }}</span>
                  <span class="arc-verdict" [class]="'v-' + av.verdict">{{ av.verdict | uppercase }}</span>
                  <span class="arc-result">{{ av.verdict === item.groundTruth ? '✅' : '❌' }}</span>
                </div>
                <div class="arc-conf">Confidence: {{ av.confidence * 100 | number:'1.0-0' }}%</div>
                <p class="arc-reasoning">{{ av.reasoning }}</p>
              </div>
              }
            </div>
          </div>
        </div>
        }

        <!-- Verdict Input (only show if not yet answered) -->
        @if (item.humanVerdict == null) {
        <div class="verdict-input">
          <h3 class="verdict-question">Is this content AI-generated or human-created?</h3>

          <div class="verdict-buttons">
            <button class="verdict-btn ai-btn" [class.selected]="pendingVerdict === 'ai'" (click)="pendingVerdict = 'ai'">
              <span class="vb-icon">🤖</span>
              <span class="vb-label">AI Generated</span>
            </button>
            <button class="verdict-btn human-btn" [class.selected]="pendingVerdict === 'human'" (click)="pendingVerdict = 'human'">
              <span class="vb-icon">👤</span>
              <span class="vb-label">Human Created</span>
            </button>
          </div>

          @if (pendingVerdict) {
          <div class="confidence-input">
            <label>Confidence Level</label>
            <div class="confidence-scale">
              @for (c of [1,2,3,4,5]; track $index) {
              <button
                class="conf-btn"
                [class.selected]="pendingConfidence === c"
                (click)="pendingConfidence = c">
                {{ c }}
              </button>
              }
            </div>
            <div class="conf-labels">
              <span>Not sure</span>
              <span>Very confident</span>
            </div>
          </div>
          }

          @if (pendingVerdict) {
          <div class="reasoning-input">
            <label>Why do you think so? (optional)</label>
            <textarea [(ngModel)]="pendingReasoning" placeholder="Describe what clues led to your decision..." rows="3"></textarea>
          </div>
          }

          <button class="submit-btn" [disabled]="!pendingVerdict || !pendingConfidence" (click)="submitAnswer()">
            {{ isLastItem() ? '✅ Submit & View Results' : '➡️ Submit & Next' }}
          </button>
        </div>
        }
      </div>
      }
    </div>
    }
    }

    <!-- Results Dashboard -->
    @if (surveyService.isComplete()) {
    <app-survey-results />
    }
  `,
  styles: [`
    .survey-container {
      max-width: 900px;
      margin: 0 auto;
      padding: 2rem;
    }

    /* Landing */
    .survey-landing {
      display: flex;
      flex-direction: column;
      gap: 2rem;
    }
    .landing-header {
      text-align: center;
      .landing-icon { font-size: 3rem; display: block; margin-bottom: 1rem; }
      h1 { margin: 0 0 0.5rem; font-size: 2rem; color: var(--text-primary); font-weight: 700; }
      .landing-subtitle { color: var(--text-muted); font-size: 1.1rem; margin: 0; }
    }
    .landing-description {
      background: var(--bg-glass); backdrop-filter: blur(var(--blur-md));
      border-radius: var(--radius-lg); padding: 2rem; border: 1px solid var(--border-default);
      p { color: var(--text-secondary); line-height: 1.8; font-size: 0.95rem; margin: 1rem 0 1.5rem; }
    }
    .research-badge {
      display: inline-flex; align-items: center; gap: 0.5rem;
      background: var(--info-bg); border: 1px solid var(--accent-cyan);
      padding: 0.4rem 1rem; border-radius: 20px; color: var(--accent-cyan);
      font-size: 0.8rem; font-weight: 600;
      .rb-icon { font-size: 1rem; }
    }
    .info-cards {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem;
    }
    .info-card {
      background: var(--bg-hover); border-radius: var(--radius-md); padding: 1.25rem;
      border: 1px solid var(--border-default); text-align: center;
      .ic-icon { font-size: 2rem; display: block; margin-bottom: 0.5rem; }
      h4 { margin: 0 0 0.4rem; color: var(--text-primary); font-size: 0.9rem; }
      p { margin: 0; color: var(--text-muted); font-size: 0.75rem; line-height: 1.5; }
    }
    .survey-config {
      background: var(--bg-glass); backdrop-filter: blur(var(--blur-md));
      border-radius: var(--radius-lg); padding: 2rem; border: 1px solid var(--border-default);
      h3 { margin: 0 0 1.5rem; color: var(--text-primary); font-size: 1.1rem; }
    }
    .config-row {
      margin-bottom: 1.25rem;
      label { display: block; color: var(--text-muted); font-size: 0.85rem; margin-bottom: 0.5rem; font-weight: 500; }
    }
    .config-options { display: flex; gap: 0.5rem; flex-wrap: wrap; }
    .config-btn {
      background: var(--bg-elevated); border: 1px solid var(--border-default);
      color: var(--text-secondary); padding: 0.6rem 1.25rem; border-radius: var(--radius-md); cursor: pointer;
      font-size: 0.9rem; transition: all 0.3s; min-height: var(--min-touch-target);
      &:hover { background: var(--bg-hover); }
      &:focus-visible { outline: 2px solid var(--focus-ring); outline-offset: 2px; }
      &.active {
        background: linear-gradient(135deg, var(--accent-cyan), var(--accent-green)); color: var(--bg-primary);
        font-weight: 600; border-color: transparent;
      }
    }
    .mode-btn {
      display: flex; align-items: center; gap: 0.5rem;
      &.collab.active { background: linear-gradient(135deg, var(--accent-purple), var(--accent-red)); color: #fff; }
    }
    .collab-note {
      background: var(--cat-c-bg); border: 1px solid var(--accent-purple);
      padding: 0.75rem 1rem; border-radius: var(--radius-md); font-size: 0.82rem;
      color: var(--accent-purple); margin: 0.5rem 0 1rem; line-height: 1.5;
    }
    .start-btn {
      width: 100%; padding: 1rem; border: none; border-radius: var(--radius-md); cursor: pointer;
      background: linear-gradient(135deg, var(--accent-cyan), var(--accent-green)); color: var(--bg-primary);
      font-size: 1.1rem; font-weight: 700; display: flex; align-items: center;
      justify-content: center; gap: 0.5rem; transition: all 0.3s; min-height: var(--min-touch-target);
      &:hover { transform: translateY(-2px); box-shadow: 0 8px 25px var(--info-bg); }
      &:focus-visible { outline: 2px solid var(--focus-ring); outline-offset: 2px; }
    }
    .consent-notice {
      display: flex; align-items: flex-start; gap: 0.75rem;
      background: var(--bg-hover); border-radius: var(--radius-md); padding: 1rem 1.5rem;
      border: 1px solid var(--border-default);
      .consent-icon { font-size: 1.25rem; flex-shrink: 0; margin-top: 2px; }
      p { margin: 0; color: var(--text-muted); font-size: 0.78rem; line-height: 1.6; }
    }

    /* Progress */
    .survey-progress {
      background: var(--bg-glass); backdrop-filter: blur(var(--blur-md));
      border-radius: var(--radius-lg); padding: 1.25rem 1.5rem; margin-bottom: 1.5rem;
      border: 1px solid var(--border-default);
    }
    .progress-info {
      display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem;
    }
    .progress-label { font-size: 0.8rem; color: var(--text-muted); }
    .progress-count { font-size: 0.85rem; color: var(--accent-cyan); font-weight: 600; }
    .progress-bar {
      height: 6px; background: var(--bg-elevated); border-radius: 3px; overflow: hidden;
      margin-bottom: 0.75rem;
    }
    .progress-fill {
      height: 100%; background: linear-gradient(90deg, var(--accent-cyan), var(--accent-green));
      border-radius: 3px; transition: width 0.4s;
    }
    .progress-items { display: flex; gap: 0.35rem; flex-wrap: wrap; }
    .progress-dot {
      width: 28px; height: 28px; border-radius: 50%; border: 1px solid var(--border-default);
      background: var(--bg-hover); color: var(--text-muted); font-size: 0.65rem;
      cursor: pointer; display: flex; align-items: center; justify-content: center;
      transition: all 0.2s;
      &.current { border-color: var(--accent-cyan); color: var(--accent-cyan); background: var(--info-bg); }
      &.answered { border-color: var(--accent-green); }
      &.correct { background: var(--human-bg); color: var(--accent-green); border-color: var(--accent-green); }
      &.wrong { background: var(--danger-bg); color: var(--accent-red); border-color: var(--accent-red); }
    }

    /* Survey Item */
    .survey-item {
      display: flex; flex-direction: column; gap: 1.25rem;
    }
    .item-header {
      display: flex; align-items: center; gap: 0.75rem; flex-wrap: wrap;
    }
    .item-number {
      font-size: 0.85rem; color: var(--accent-cyan); font-weight: 600;
      background: var(--info-bg); padding: 0.3rem 0.75rem; border-radius: var(--radius-sm);
    }
    .item-category {
      font-size: 0.75rem; color: var(--text-secondary); background: var(--bg-elevated);
      padding: 0.2rem 0.6rem; border-radius: var(--radius-sm);
    }
    .item-difficulty {
      font-size: 0.65rem; font-weight: 700; padding: 0.2rem 0.5rem; border-radius: var(--radius-sm);
      text-transform: uppercase; letter-spacing: 0.5px;
      &.diff-easy { background: var(--human-bg); color: var(--accent-green); }
      &.diff-medium { background: var(--warning-bg); color: var(--accent-orange); }
      &.diff-hard { background: var(--danger-bg); color: var(--accent-red); }
    }
    .item-type {
      font-size: 0.65rem; color: var(--text-muted); background: var(--bg-hover);
      padding: 0.2rem 0.5rem; border-radius: var(--radius-sm);
    }
    .item-content-card {
      background: var(--bg-glass); backdrop-filter: blur(var(--blur-md));
      border-radius: var(--radius-lg); padding: 2rem; border: 1px solid var(--border-default);
    }
    .item-title {
      margin: 0 0 1rem; color: var(--text-primary); font-size: 1.2rem; font-weight: 600;
    }
    .item-content {
      margin: 0; color: var(--text-secondary); font-size: 1rem; line-height: 1.8;
    }
    .item-image {
      width: 100%; border-radius: var(--radius-md); margin-top: 1rem; max-height: 400px; object-fit: cover;
    }

    /* Collab Hints */
    .collab-hints {
      background: var(--bg-glass); backdrop-filter: blur(var(--blur-sm));
      border-radius: var(--radius-lg); padding: 1.25rem; border: 1px solid var(--accent-purple);
    }
    .collab-header {
      display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1rem;
      .collab-icon { font-size: 1.2rem; }
      .collab-title { font-size: 0.85rem; color: var(--accent-purple); font-weight: 600; }
    }
    .agent-hints-grid {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 0.75rem;
    }
    .agent-hint {
      background: var(--bg-hover); border-radius: var(--radius-md); padding: 0.75rem;
      border: 1px solid var(--border-default);
    }
    .hint-header {
      display: flex; align-items: center; gap: 0.4rem; margin-bottom: 0.4rem;
    }
    .hint-flag { font-size: 1.1rem; }
    .hint-region { font-size: 0.75rem; color: var(--text-secondary); font-weight: 600; flex: 1; }
    .hint-verdict {
      font-size: 0.6rem; font-weight: 700; padding: 0.15rem 0.4rem; border-radius: var(--radius-sm);
      &.v-ai { background: var(--ai-bg); color: var(--accent-red); }
      &.v-human { background: var(--human-bg); color: var(--accent-green); }
    }
    .hint-conf { font-size: 0.65rem; color: var(--text-muted); }
    .hint-reasoning { margin: 0; font-size: 0.7rem; color: var(--text-muted); line-height: 1.5; }

    /* Post-answer review */
    .already-answered {
      display: flex; flex-direction: column; gap: 1rem;
    }
    .answer-summary {
      display: flex; align-items: center; gap: 1rem; padding: 1rem 1.5rem;
      border-radius: var(--radius-md);
      &.correct { background: var(--human-bg); border: 1px solid var(--accent-green); }
      &.wrong { background: var(--danger-bg); border: 1px solid var(--accent-red); }
      .answer-icon { font-size: 1.5rem; }
      .answer-details {
        display: flex; flex-direction: column; gap: 0.2rem;
        span { font-size: 0.85rem; color: var(--text-secondary); }
      }
    }
    .post-answer-agents {
      h4 { margin: 0 0 0.75rem; color: var(--text-muted); font-size: 0.9rem; }
    }
    .agent-grid-review {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 0.6rem;
    }
    .agent-review-card {
      padding: 0.75rem; border-radius: var(--radius-md);
      border: 1px solid var(--border-default); background: var(--bg-hover);
      &.agent-correct { border-color: var(--accent-green); }
      &.agent-wrong { border-color: var(--accent-red); }
    }
    .arc-header {
      display: flex; align-items: center; gap: 0.4rem; margin-bottom: 0.3rem;
      font-size: 0.78rem; color: var(--text-secondary); font-weight: 500;
    }
    .arc-verdict {
      font-size: 0.6rem; font-weight: 700; padding: 0.1rem 0.35rem; border-radius: 4px; margin-left: auto;
      &.v-ai { background: var(--ai-bg); color: var(--accent-red); }
      &.v-human { background: var(--human-bg); color: var(--accent-green); }
    }
    .arc-result { font-size: 0.85rem; }
    .arc-conf { font-size: 0.65rem; color: var(--text-muted); margin-bottom: 0.2rem; }
    .arc-reasoning { margin: 0; font-size: 0.68rem; color: var(--text-muted); line-height: 1.4; }

    /* Verdict Input */
    .verdict-input {
      background: var(--bg-glass); backdrop-filter: blur(var(--blur-md));
      border-radius: var(--radius-lg); padding: 2rem; border: 1px solid var(--border-default);
    }
    .verdict-question {
      margin: 0 0 1.5rem; color: var(--text-primary); font-size: 1.1rem; text-align: center;
    }
    .verdict-buttons {
      display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 1.5rem;
    }
    .verdict-btn {
      padding: 1.5rem; border-radius: var(--radius-lg); cursor: pointer; text-align: center;
      border: 2px solid var(--border-default); background: var(--bg-hover);
      transition: all 0.3s; display: flex; flex-direction: column; align-items: center; gap: 0.5rem;
      min-height: var(--min-touch-target);
      .vb-icon { font-size: 2.5rem; }
      .vb-label { font-size: 1rem; color: var(--text-secondary); font-weight: 600; }
      &:hover { transform: translateY(-3px); background: var(--bg-elevated); }
      &:focus-visible { outline: 2px solid var(--focus-ring); outline-offset: 2px; }
      &.ai-btn.selected {
        border-color: var(--accent-red); background: var(--ai-bg);
        box-shadow: 0 8px 25px var(--ai-bg);
        .vb-label { color: var(--accent-red); }
      }
      &.human-btn.selected {
        border-color: var(--accent-green); background: var(--human-bg);
        box-shadow: 0 8px 25px var(--human-bg);
        .vb-label { color: var(--accent-green); }
      }
    }
    .confidence-input {
      margin-bottom: 1.25rem;
      label { display: block; color: var(--text-muted); font-size: 0.85rem; margin-bottom: 0.5rem; }
    }
    .confidence-scale { display: flex; gap: 0.5rem; justify-content: center; margin-bottom: 0.3rem; }
    .conf-btn {
      width: 48px; height: 48px; border-radius: 50%; cursor: pointer;
      background: var(--bg-elevated); border: 1px solid var(--border-default);
      color: var(--text-secondary); font-size: 1rem; font-weight: 600; transition: all 0.3s;
      &:hover { background: var(--bg-hover); }
      &:focus-visible { outline: 2px solid var(--focus-ring); outline-offset: 2px; }
      &.selected {
        background: linear-gradient(135deg, var(--accent-cyan), var(--accent-green)); color: var(--bg-primary);
        border-color: transparent; transform: scale(1.1);
      }
    }
    .conf-labels {
      display: flex; justify-content: space-between;
      span { font-size: 0.7rem; color: var(--text-muted); }
    }
    .reasoning-input {
      margin-bottom: 1.5rem;
      label { display: block; color: var(--text-muted); font-size: 0.85rem; margin-bottom: 0.5rem; }
      textarea {
        width: 100%; background: var(--bg-elevated); border: 1px solid var(--border-default);
        border-radius: var(--radius-md); padding: 0.75rem; color: var(--text-secondary); font-size: 0.9rem;
        resize: vertical; font-family: inherit;
        &::placeholder { color: var(--text-muted); }
        &:focus { outline: none; border-color: var(--accent-cyan); }
      }
    }
    .submit-btn {
      width: 100%; padding: 1rem; border: none; border-radius: var(--radius-md); cursor: pointer;
      background: linear-gradient(135deg, var(--accent-cyan), var(--accent-green)); color: var(--bg-primary);
      font-size: 1rem; font-weight: 700; transition: all 0.3s; min-height: var(--min-touch-target);
      &:hover:not(:disabled) { transform: translateY(-2px); box-shadow: 0 8px 25px var(--info-bg); }
      &:focus-visible { outline: 2px solid var(--focus-ring); outline-offset: 2px; }
      &:disabled { opacity: 0.4; cursor: not-allowed; }
    }

    @media (forced-colors: active) {
      .verdict-btn, .config-btn, .conf-btn, .progress-dot { border: 1px solid ButtonText; }
      .vote-fill, .progress-fill { forced-color-adjust: none; }
    }

    @media (max-width: 600px) {
      .survey-container { padding: 1rem; }
      .verdict-buttons { grid-template-columns: 1fr; }
      .agent-hints-grid, .agent-grid-review { grid-template-columns: 1fr; }
      .info-cards { grid-template-columns: 1fr 1fr; }
    }
  `]
})
export class SurveyComponent {
  surveyService = inject(SurveyService);

  selectedCount = 10;
  collabMode = false;
  itemCounts = [5, 8, 10, 12, 16];

  pendingVerdict: 'ai' | 'human' | null = null;
  pendingConfidence: number | null = null;
  pendingReasoning = '';

  private regionFlags: Record<string, string> = {
    'Africa': '🌍', 'Asia': '🌏', 'Europe': '🇪🇺', 'Americas': '🌎', 'Oceania': '🏝️',
  };

  startSurvey(): void {
    this.surveyService.startSession(this.selectedCount, this.collabMode);
  }

  getRegionFlag(region: string): string {
    return this.regionFlags[this.getDisplayRegion(region)] ?? '🌐';
  }

  getDisplayRegion(region: string): string {
    const normalized: Record<string, string> = {
      North_America: 'Americas',
      South_America: 'Americas',
      Antarctica: 'Oceania',
      Australia: 'Oceania',
    };
    return normalized[region] ?? region;
  }

  isLastItem(): boolean {
    const s = this.surveyService.session();
    return s ? s.currentIndex === s.items.length - 1 : false;
  }

  submitAnswer(): void {
    if (!this.pendingVerdict || !this.pendingConfidence) return;
    this.surveyService.submitVerdict(this.pendingVerdict, this.pendingConfidence, this.pendingReasoning);
    this.pendingVerdict = null;
    this.pendingConfidence = null;
    this.pendingReasoning = '';
  }
}
