import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-consent-waiver',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="consent-container">
      <div class="consent-card">
        <div class="consent-header">
          <span class="header-icon">📜</span>
          <h1>Informed Consent — Waiver of Written Documentation</h1>
        </div>

        <div class="consent-body">
          <!-- Study Overview -->
          <section class="consent-section">
            <h2><span class="section-icon">🔬</span> Study Overview</h2>
            <p>
              You are being invited to participate in a research study titled
              <strong>"TrustFeed: Human-in-the-Loop Multi-Agent AI for Data Authenticity Assessment."</strong>
              This study investigates how humans and AI agents collaborate to identify AI-generated
              versus human-created content across text, image, and video media.
            </p>
            <p>
              This research is conducted as part of an academic project at the
              University of North Carolina at Charlotte (UNCC), ITIS-5360 course.
            </p>
          </section>

          <!-- Waiver of Written Documentation -->
          <section class="consent-section highlight">
            <h2><span class="section-icon">📋</span> Waiver of Written Documentation of Consent</h2>
            <p>
              Because this is an <strong>internet-based survey</strong>, a signed consent form is
              <strong>impractical</strong> and not required. In accordance with federal regulations
              (45 CFR 46.117(c)), the IRB has waived the requirement for a signed written consent
              document for this study. Your voluntary participation after reviewing this information
              constitutes your informed consent.
            </p>
          </section>

          <!-- What You Will Do -->
          <section class="consent-section">
            <h2><span class="section-icon">🎯</span> What You Will Be Asked To Do</h2>
            <ul>
              <li>View 5–16 content items (text, images, or videos) fetched from free internet sources.</li>
              <li>For each item, decide whether it was <strong>created by a human</strong> or
                <strong>generated by AI</strong>.</li>
              <li>Optionally participate in <strong>Human-AI Collaboration mode</strong>, where five
                continental AI agents provide their verdicts before you make your decision.</li>
              <li>The session typically takes <strong>5–15 minutes</strong> depending on the number of items selected.</li>
            </ul>
          </section>

          <!-- Risks -->
          <section class="consent-section">
            <h2><span class="section-icon">⚠️</span> Risks &amp; Discomforts</h2>
            <p>
              This study presents <strong>minimal risk</strong>. Content items are sourced from
              publicly available internet sources (Wikipedia, Picsum Photos, Pexels, Pollinations AI).
              You may encounter content that you find uninteresting or mildly challenging to classify,
              but no harmful, offensive, or sensitive material is intentionally included.
            </p>
          </section>

          <!-- Benefits -->
          <section class="consent-section">
            <h2><span class="section-icon">✅</span> Benefits</h2>
            <p>
              There are no direct benefits to you for participating. Your responses will contribute to
              research on human-AI interaction, content authenticity verification, and the study of
              regional AI bias patterns, which may benefit society's understanding of AI trustworthiness.
            </p>
          </section>

          <!-- Data Privacy -->
          <section class="consent-section highlight">
            <h2><span class="section-icon">🔒</span> Data Privacy &amp; No PII Policy</h2>
            <p>
              This study enforces a strict <strong>No Personally Identifiable Information (PII)</strong> policy:
            </p>
            <ul>
              <li><strong>No names, emails, IP addresses, or demographics</strong> are collected.</li>
              <li>Sessions are identified only by an anonymous timestamp-based ID
                (e.g., <code>session-1711400000000</code>).</li>
              <li>All data is stored in a MySQL database with no PII columns.</li>
              <li>Only your verdicts (AI/Human), confidence levels, and response times are recorded.</li>
              <li>Aggregated results are used solely for academic research purposes.</li>
            </ul>
          </section>

          <!-- Voluntary Participation -->
          <section class="consent-section">
            <h2><span class="section-icon">🤝</span> Voluntary Participation</h2>
            <p>
              Your participation is <strong>entirely voluntary</strong>. You may choose not to
              participate or stop participating at any time without penalty. You may close the
              browser window at any point to withdraw. Incomplete sessions will not be included in
              the final analysis.
            </p>
          </section>

          <!-- Contact -->
          <section class="consent-section">
            <h2><span class="section-icon">📧</span> Contact Information</h2>
            <p>
              If you have questions about this study, you may contact the research team through the
              ITIS-5360 course at the University of North Carolina at Charlotte.
            </p>
          </section>

          <!-- Full / Partial Waiver Notice -->
          <section class="consent-section waiver-notice">
            <h2><span class="section-icon">📌</span> Full &amp; Partial Waiver of Consent</h2>
            <p>
              In accordance with IRB guidelines, a <strong>full waiver of signed consent</strong>
              is applied to this study because:
            </p>
            <ul>
              <li>The research involves <strong>no more than minimal risk</strong> to participants.</li>
              <li>The waiver will <strong>not adversely affect</strong> the rights and welfare of participants.</li>
              <li>The research could <strong>not practicably be carried out</strong> without the waiver,
                as it is conducted entirely online.</li>
              <li>Whenever appropriate, participants are provided with pertinent information
                <strong>after participation</strong> via the results dashboard.</li>
            </ul>
          </section>
        </div>

        <!-- Agreement Section -->
        <div class="consent-agreement">
          <label class="checkbox-label" (click)="toggleConsent()">
            <div class="custom-checkbox" [class.checked]="consentGiven()">
              <span *ngIf="consentGiven()">✓</span>
            </div>
            <span>
              I have read and understand the above information. I understand that my participation
              is voluntary, no personal data is collected, and I may withdraw at any time. I agree
              to participate in this research study.
            </span>
          </label>
        </div>

        <div class="consent-actions">
          <button class="proceed-btn" [disabled]="!consentGiven()" (click)="proceed()">
            <span>🚀</span> Proceed to Survey
          </button>
          <p class="decline-text">
            If you do not wish to participate, simply close this browser window.
          </p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .consent-container {
      min-height: calc(100vh - 64px);
      display: flex;
      justify-content: center;
      padding: 2rem 1rem;
      background: var(--bg-primary);
    }

    .consent-card {
      max-width: 820px;
      width: 100%;
      background: var(--bg-secondary);
      border: 1px solid var(--border-default);
      border-radius: var(--radius-lg);
      overflow: hidden;
    }

    .consent-header {
      text-align: center;
      padding: 2rem 2rem 1.5rem;
      background: var(--bg-tertiary);
      border-bottom: 1px solid var(--border-default);
    }

    .header-icon {
      font-size: 2.5rem;
      display: block;
      margin-bottom: 0.5rem;
    }

    .consent-header h1 {
      color: var(--text-primary);
      font-size: 1.5rem;
      margin: 0 0 0.5rem;
      font-weight: 700;
    }

    .irb-badge {
      display: inline-block;
      padding: 0.35rem 1rem;
      background: var(--cat-a-bg);
      border: 1px solid var(--accent-primary);
      border-radius: var(--radius-full);
      color: var(--accent-primary);
      font-size: 0.8rem;
      font-weight: 600;
      letter-spacing: 0.5px;
      margin: 0;
    }

    .consent-body {
      padding: 1.5rem 2rem;
      max-height: 55vh;
      overflow-y: auto;
    }

    .consent-body::-webkit-scrollbar { width: 6px; }
    .consent-body::-webkit-scrollbar-track { background: var(--bg-tertiary); }
    .consent-body::-webkit-scrollbar-thumb { background: var(--bg-elevated); border-radius: 3px; }

    .consent-section {
      margin-bottom: 1.5rem;
      padding-bottom: 1.5rem;
      border-bottom: 1px solid var(--border-subtle);
    }

    .consent-section:last-child {
      border-bottom: none;
      margin-bottom: 0;
    }

    .consent-section h2 {
      color: var(--text-primary);
      font-size: 1.05rem;
      margin: 0 0 0.75rem;
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .section-icon { font-size: 1.1rem; }

    .consent-section p {
      color: var(--text-muted);
      font-size: 0.9rem;
      line-height: 1.7;
      margin: 0 0 0.5rem;
    }

    .consent-section ul {
      color: var(--text-muted);
      font-size: 0.9rem;
      line-height: 1.7;
      margin: 0.5rem 0 0;
      padding-left: 1.5rem;
    }

    .consent-section ul li { margin-bottom: 0.4rem; }

    .consent-section code {
      background: var(--bg-elevated);
      padding: 0.15rem 0.4rem;
      border-radius: 4px;
      font-size: 0.82rem;
      color: var(--accent-primary);
    }

    .consent-section.highlight {
      background: var(--cat-a-bg);
      border: 1px solid var(--accent-primary);
      border-radius: var(--radius-md);
      padding: 1.2rem 1.5rem;
      margin-left: -0.5rem;
      margin-right: -0.5rem;
    }

    .consent-section.waiver-notice {
      background: var(--status-notice-bg);
      border: 1px solid var(--status-notice);
      border-radius: var(--radius-md);
      padding: 1.2rem 1.5rem;
      margin-left: -0.5rem;
      margin-right: -0.5rem;
    }

    .consent-agreement {
      padding: 1.5rem 2rem;
      border-top: 1px solid var(--border-default);
      background: var(--bg-tertiary);
    }

    .checkbox-label {
      display: flex;
      align-items: flex-start;
      gap: 1rem;
      cursor: pointer;
      user-select: none;
    }

    .custom-checkbox {
      flex-shrink: 0;
      width: 24px;
      height: 24px;
      border: 2px solid var(--accent-primary);
      border-radius: var(--radius-sm);
      display: flex;
      align-items: center;
      justify-content: center;
      transition: all 0.2s;
      margin-top: 2px;
      color: var(--text-inverse);
      font-size: 0.85rem;
      font-weight: 700;
    }

    .custom-checkbox.checked {
      background: var(--accent-primary);
      border-color: var(--accent-primary);
    }

    .checkbox-label span:last-child {
      color: var(--text-secondary);
      font-size: 0.88rem;
      line-height: 1.6;
    }

    .consent-actions {
      padding: 1rem 2rem 2rem;
      text-align: center;
    }

    .proceed-btn {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.9rem 2.5rem;
      background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary));
      color: var(--text-inverse);
      border: none;
      border-radius: var(--radius-md);
      font-size: 1.05rem;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.3s;
      min-height: var(--min-touch-target);
    }

    .proceed-btn:hover:not(:disabled) {
      transform: translateY(-2px);
      box-shadow: var(--shadow-lg);
    }

    .proceed-btn:disabled {
      opacity: 0.4;
      cursor: not-allowed;
    }

    .decline-text {
      color: var(--text-muted);
      font-size: 0.8rem;
      margin-top: 1rem;
    }

    @media (forced-colors: active) {
      .consent-card { border: 2px solid CanvasText; }
      .custom-checkbox { border: 2px solid ButtonText; }
      .custom-checkbox.checked { background: Highlight; }
      .proceed-btn { border: 2px solid ButtonText; }
    }

    @media (max-width: 640px) {
      .consent-header h1 { font-size: 1.2rem; }
      .consent-body { padding: 1rem; max-height: 50vh; }
      .consent-agreement { padding: 1rem; }
      .consent-actions { padding: 1rem; }
    }
  `],
})
export class ConsentWaiverComponent {
  consentGiven = signal(false);

  constructor(private router: Router) {}

  toggleConsent(): void {
    this.consentGiven.update(v => !v);
  }

  proceed(): void {
    if (this.consentGiven()) {
      sessionStorage.setItem('consent_accepted', 'true');
      this.router.navigate(['/survey']);
    }
  }
}
