/**
 * ContentFetcher — Loads content from local dataset files.
 * Content is sourced from AugmentedDoing/dataset/ directory organized by continent.
 * Each continent has Text/Images/Videos with AI/NonAI subfolders.
 * NO PII collected. All content is pre-curated.
 */

const fs = require('fs');
const path = require('path');

// ─── Dataset root path ───
// In Docker: /app/dataset (copied by Dockerfile)
// Local dev: ../../AugmentedDoing/dataset (relative to server/)
const DOCKER_DATASET = path.resolve(__dirname, 'dataset');
const LOCAL_DATASET = path.resolve(__dirname, '..', '..', 'AugmentedDoing', 'dataset');
const DATASET_ROOT = fs.existsSync(DOCKER_DATASET) ? DOCKER_DATASET : LOCAL_DATASET;

const CONTINENTS = ['Africa', 'Asia', 'Europe', 'North_America', 'South_America', 'Antarctica', 'Australia'];

// ─── Load text items from a continent ───

function loadTextItems(continent) {
  const items = [];
  const basePath = path.join(DATASET_ROOT, continent, 'Text');

  for (const label of ['AI', 'NonAI']) {
    const folder = path.join(basePath, label);
    if (!fs.existsSync(folder)) continue;

    const files = fs.readdirSync(folder).filter(f => f.endsWith('.json'));
    for (const file of files) {
      try {
        const data = JSON.parse(fs.readFileSync(path.join(folder, file), 'utf-8'));
        const title = data.title || file.replace(/\.json$/, '').replace(/_/g, ' ');
        const content = data.extract || data.content || '';
        if (!content || content.length < 20) continue;

        items.push({
          title,
          content,
          imageUrl: data.thumbnail?.source || null,
          contentType: 'text',
          groundTruth: label === 'AI' ? 'ai' : 'human',
          category: data.category || data.description || 'General',
          difficulty: data.difficulty || assignDifficulty(content),
          source: `dataset-${continent}`,
          continent,
        });
      } catch (err) {
        console.error(`Error loading ${folder}/${file}:`, err.message);
      }
    }
  }
  return items;
}

// ─── Load image items from a continent ───

function loadImageItems(continent) {
  const items = [];
  const basePath = path.join(DATASET_ROOT, continent, 'Images');

  for (const label of ['AI', 'NonAI']) {
    const folder = path.join(basePath, label);
    if (!fs.existsSync(folder)) continue;

    const files = fs.readdirSync(folder).filter(f => /\.(jpg|jpeg|png|gif|webp)$/i.test(f));
    for (const file of files) {
      const title = file.replace(/\.[^.]+$/, '').replace(/_/g, ' ');
      const filePath = path.join(folder, file);

      items.push({
        title,
        content: label === 'AI'
          ? `This image was generated by AI. It demonstrates generative AI capabilities in visual content creation from the ${continent.replace('_', ' ')} dataset.`
          : `A real photograph from ${continent.replace('_', ' ')}. This image showcases authentic human photography with natural composition and lighting.`,
        imageUrl: `/api/dataset-file?path=${encodeURIComponent(path.relative(DATASET_ROOT, filePath).replace(/\\/g, '/'))}`,
        contentType: 'image',
        groundTruth: label === 'AI' ? 'ai' : 'human',
        category: label === 'AI' ? 'AI Art' : 'Photography',
        difficulty: 'medium',
        source: `dataset-${continent}`,
        continent,
      });
    }
  }
  return items;
}

// ─── Load video items from a continent ───

function loadVideoItems(continent) {
  const items = [];
  const basePath = path.join(DATASET_ROOT, continent, 'Videos');

  for (const label of ['AI', 'NonAI']) {
    const folder = path.join(basePath, label);
    if (!fs.existsSync(folder)) continue;

    const files = fs.readdirSync(folder).filter(f => /\.(mp4|webm|mov)$/i.test(f));
    for (const file of files) {
      const title = file.replace(/\.[^.]+$/, '').replace(/_/g, ' ');
      const filePath = path.join(folder, file);

      items.push({
        title,
        content: label === 'AI'
          ? `An AI-generated video from the ${continent.replace('_', ' ')} dataset. Synthetic visual content created by generative models.`
          : `Real-world video footage from ${continent.replace('_', ' ')}. Authentic human-captured videography with natural movement.`,
        videoUrl: `/api/dataset-file?path=${encodeURIComponent(path.relative(DATASET_ROOT, filePath).replace(/\\/g, '/'))}`,
        imageUrl: null,
        contentType: 'video',
        groundTruth: label === 'AI' ? 'ai' : 'human',
        category: label === 'AI' ? 'AI Video' : 'Video',
        difficulty: 'hard',
        source: `dataset-${continent}`,
        continent,
      });
    }
  }
  return items;
}

// ─── Difficulty assignment ───

function assignDifficulty(text) {
  const wordCount = text.split(/\s+/).length;
  const avgWordLen = text.replace(/\s+/g, '').length / wordCount;
  if (avgWordLen > 6 && wordCount > 100) return 'hard';
  if (avgWordLen > 5 || wordCount > 60) return 'medium';
  return 'easy';
}

// ─── Main fetch orchestrator — loads from local dataset ───

async function fetchUniqueContent(totalCount, _pexelsApiKey) {
  let allContent = [];

  // Load content from all continents
  for (const continent of CONTINENTS) {
    allContent.push(
      ...loadTextItems(continent),
      ...loadImageItems(continent),
      ...loadVideoItems(continent),
    );
  }

  // Shuffle
  allContent = allContent.sort(() => Math.random() - 0.5);

  // Ensure balanced ground truth (~50/50 human/ai)
  const humanItems = allContent.filter(c => c.groundTruth === 'human');
  const aiItems = allContent.filter(c => c.groundTruth === 'ai');

  // Pick balanced set
  const halfCount = Math.ceil(totalCount / 2);
  const selectedHuman = humanItems.sort(() => Math.random() - 0.5).slice(0, halfCount);
  const selectedAi = aiItems.sort(() => Math.random() - 0.5).slice(0, totalCount - selectedHuman.length);

  let selected = [...selectedHuman, ...selectedAi].sort(() => Math.random() - 0.5).slice(0, totalCount);

  // If we don't have enough, pad with whatever is available
  if (selected.length < totalCount) {
    const remaining = allContent.filter(c => !selected.includes(c));
    selected = [...selected, ...remaining.slice(0, totalCount - selected.length)];
  }

  return selected.map((item, i) => ({
    ...item,
    id: `content-${Date.now()}-${i}`,
  }));
}

module.exports = { fetchUniqueContent, DATASET_ROOT };
