"""Centralized OpenRouter API integration for TrustFeed.

Provides three capabilities:
  1. Text analysis — AI content detection & bias scoring via GPT-4o (OpenRouter)
  2. Image analysis — AI-generated image detection via GPT-4o Vision (OpenRouter)
  3. Embeddings  — Semantic similarity for content comparison

Uses the OpenAI Python SDK with OpenRouter's compatible endpoint.
All methods gracefully fall back to None when OPENROUTER_API_KEY is not set
or the API call fails, allowing callers to use their existing logic.
"""

from __future__ import annotations

import base64
import json
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)

_client = None  # lazy singleton


OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"


def _get_client():
    """Return the shared OpenRouter client, or None if no API key is set."""
    global _client
    if _client is not None:
        return _client
    api_key = os.getenv("OPENROUTER_API_KEY", "").strip()
    if not api_key:
        return None
    try:
        from openai import OpenAI
        _client = OpenAI(
            api_key=api_key,
            base_url=OPENROUTER_BASE_URL,
            default_headers={
                "HTTP-Referer": "https://trustfeed-core-bbiuj.ondigitalocean.app",
                "X-Title": "TrustFeed",
            },
        )
        return _client
    except Exception as exc:
        logger.warning("Failed to initialize OpenRouter client: %s", exc)
        return None


def is_available() -> bool:
    """Return True if OpenRouter can be used (API key present)."""
    return _get_client() is not None


# ─── Configuration helpers ───────────────────────────────────────────────────

def _cfg(key: str, default):
    """Read a config value from loaded YAML (imported lazily to avoid cycles)."""
    try:
        import yaml
        cfg_path = Path(__file__).resolve().parent.parent / "config" / "default.yaml"
        with open(cfg_path) as f:
            cfg = yaml.safe_load(f)
        return cfg.get(key, default)
    except Exception:
        return default


# ─── 1. TEXT ANALYSIS ────────────────────────────────────────────────────────

@dataclass
class OpenAITextResult:
    ai_probability: float          # 0-1 how likely the text is AI-generated
    confidence: float              # 0-1 model confidence
    reasoning: str                 # human-readable explanation
    detected_patterns: list[str]   # list of AI indicators found
    bias_indicators: list[str]     # bias-related phrases or framing
    features: dict = field(default_factory=dict)


_TEXT_SYSTEM_PROMPT = """You are an expert AI-content forensics analyst. Given a piece of text, determine whether it was written by a human or generated by AI (e.g., ChatGPT, Claude, Gemini).

Analyze the following dimensions:
1. Linguistic patterns (formulaic phrases, hedging, excessive politeness)
2. Structural patterns (listicle style, uniform paragraph length, predictable flow)
3. Statistical patterns (word diversity, sentence length variation)
4. Bias indicators (regional framing, cultural assumptions, loaded language)

Respond in this exact JSON format (no markdown, no extra text):
{
  "ai_probability": <float 0-1>,
  "confidence": <float 0-1>,
  "reasoning": "<brief explanation>",
  "detected_patterns": ["<pattern1>", "<pattern2>"],
  "bias_indicators": ["<indicator1>", "<indicator2>"],
  "avg_word_length": <float>,
  "lexical_diversity": <float 0-1>,
  "perplexity_estimate": <float 0-100>
}"""


def analyze_text(content: str) -> OpenAITextResult | None:
    """Analyze text content for AI-generation likelihood using GPT-4o.

    Returns None if OpenAI is unavailable or the call fails.
    """
    client = _get_client()
    if client is None:
        return None

    text = content.strip()[:4000]  # limit input size
    model = _cfg("openrouter_model", "openai/gpt-4o")
    max_tokens = _cfg("openrouter_max_tokens", 1024)
    temperature = _cfg("openrouter_temperature", 0.2)

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": _TEXT_SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this content:\n\n{text}"},
            ],
            max_tokens=max_tokens,
            temperature=temperature,
            response_format={"type": "json_object"},
        )

        raw = response.choices[0].message.content
        data = json.loads(raw)

        return OpenAITextResult(
            ai_probability=max(0.0, min(1.0, float(data.get("ai_probability", 0.5)))),
            confidence=max(0.0, min(1.0, float(data.get("confidence", 0.5)))),
            reasoning=str(data.get("reasoning", "")),
            detected_patterns=list(data.get("detected_patterns", [])),
            bias_indicators=list(data.get("bias_indicators", [])),
            features={
                "avg_word_length": float(data.get("avg_word_length", 0)),
                "lexical_diversity": float(data.get("lexical_diversity", 0)),
                "perplexity_estimate": float(data.get("perplexity_estimate", 0)),
                "source": "openrouter-" + model,
            },
        )
    except Exception as exc:
        logger.warning("OpenRouter text analysis failed: %s", exc)
        return None


# ─── 2. IMAGE ANALYSIS (GPT-4o Vision) ──────────────────────────────────────

@dataclass
class OpenAIImageResult:
    ai_probability: float
    confidence: float
    reasoning: str
    detected_artifacts: list[str]
    style_classification: str      # e.g. "photorealistic", "digital art", "screenshot"


_IMAGE_SYSTEM_PROMPT = """You are an expert in detecting AI-generated images. Analyze the provided image for signs of AI generation (e.g., DALL-E, Midjourney, Stable Diffusion).

Look for:
1. Anatomical anomalies (extra fingers, asymmetric features, malformed text)
2. Texture inconsistencies (smooth regions vs over-detailed areas)
3. Lighting inconsistencies (mismatched shadows, impossible reflections)
4. Background artifacts (blurred or nonsensical background elements)
5. Style markers (hyper-polished look common in AI art)

Respond in this exact JSON format (no markdown, no extra text):
{
  "ai_probability": <float 0-1>,
  "confidence": <float 0-1>,
  "reasoning": "<brief explanation>",
  "detected_artifacts": ["<artifact1>", "<artifact2>"],
  "style_classification": "<style>"
}"""


def analyze_image(
    *,
    image_url: str | None = None,
    image_path: str | None = None,
) -> OpenAIImageResult | None:
    """Analyze an image for AI-generation likelihood using GPT-4o Vision.

    Accepts either a URL or a local file path.
    Returns None if OpenAI is unavailable or the call fails.
    """
    client = _get_client()
    if client is None:
        return None

    model = _cfg("openrouter_model", "openai/gpt-4o")

    # Build the image content part
    image_content: dict
    if image_url:
        image_content = {"type": "image_url", "image_url": {"url": image_url, "detail": "low"}}
    elif image_path and Path(image_path).is_file():
        path = Path(image_path)
        suffix = path.suffix.lower().lstrip(".")
        mime = {"jpg": "jpeg", "jpeg": "jpeg", "png": "png", "gif": "gif", "webp": "webp"}.get(suffix, "jpeg")
        data_b64 = base64.b64encode(path.read_bytes()).decode()
        image_content = {
            "type": "image_url",
            "image_url": {"url": f"data:image/{mime};base64,{data_b64}", "detail": "low"},
        }
    else:
        return None

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": _IMAGE_SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": "Analyze this image for AI-generation indicators:"},
                        image_content,
                    ],
                },
            ],
            max_tokens=512,
            temperature=0.2,
            response_format={"type": "json_object"},
        )

        raw = response.choices[0].message.content
        data = json.loads(raw)

        return OpenAIImageResult(
            ai_probability=max(0.0, min(1.0, float(data.get("ai_probability", 0.5)))),
            confidence=max(0.0, min(1.0, float(data.get("confidence", 0.5)))),
            reasoning=str(data.get("reasoning", "")),
            detected_artifacts=list(data.get("detected_artifacts", [])),
            style_classification=str(data.get("style_classification", "unknown")),
        )
    except Exception as exc:
        logger.warning("OpenRouter image analysis failed: %s", exc)
        return None


# ─── 3. EMBEDDINGS (Semantic Similarity) ────────────────────────────────────

def get_embedding(text: str) -> list[float] | None:
    """Get an embedding vector for the given text.

    Returns None if OpenAI is unavailable.
    """
    client = _get_client()
    if client is None:
        return None

    model = _cfg("openrouter_embedding_model", "openai/text-embedding-3-small")

    try:
        response = client.embeddings.create(
            model=model,
            input=text.strip()[:8000],
        )
        return response.data[0].embedding
    except Exception as exc:
        logger.warning("OpenRouter embedding failed: %s", exc)
        return None


def compute_similarity(text_a: str, text_b: str) -> float | None:
    """Compute cosine similarity between two texts using OpenAI embeddings.

    Returns a float 0-1, or None if unavailable.
    """
    emb_a = get_embedding(text_a)
    emb_b = get_embedding(text_b)
    if emb_a is None or emb_b is None:
        return None

    # Cosine similarity
    dot = sum(a * b for a, b in zip(emb_a, emb_b))
    norm_a = sum(a * a for a in emb_a) ** 0.5
    norm_b = sum(b * b for b in emb_b) ** 0.5
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return max(0.0, min(1.0, dot / (norm_a * norm_b)))
